/* ============================================
   AI MAP - Layer & Taxonomy Data
   ============================================ */

const LAYERS = [
  {
    id: 'energy',
    label: 'Energy',
    sub: 'Power generation, grid supply, electricity economics',
    desc: 'Every AI system begins with electricity. You cannot generate intelligence without generating power first. The energy layer is the hard floor. It determines how much compute a country, a company, or a data center can sustain. Progress here is measured in gigawatts secured, not algorithms written.',
    w: 100,
  },
  {
    id: 'chips',
    label: 'Chips',
    sub: 'GPUs, TPUs, ASICs, memory, interconnects',
    desc: 'Chips convert energy into computation. AI workloads require massive parallelism, high-bandwidth memory, and fast interconnects, a fundamentally different design point from general-purpose CPUs. The economics of intelligence are set at the silicon level: who has the chips controls the throughput.',
    w: 88,
  },
  {
    id: 'infra',
    label: 'Infrastructure',
    sub: 'CUDA, distributed systems, serving, MLOps, AI factories',
    desc: 'Infrastructure turns hardware into production capacity. This layer covers everything from CUDA and compiler stacks to distributed training frameworks, inference engines, and the orchestration systems that keep clusters running. AI factories belong here: the physical and software systems that turn racks of GPUs into reliable intelligence production.',
    w: 74,
  },
  {
    id: 'models',
    label: 'Models',
    sub: 'Architectures, learning paradigms, alignment, multimodal, world models',
    desc: 'Models are the intelligence layer. Not just large language models, but the full range of architectures and training methods that turn data into capability. This includes transformers, diffusion models, reinforcement learning, multimodal systems, world models, and the alignment research that keeps them reliable. The diversity here matters: language is one modality among many.',
    w: 62,
  },
  {
    id: 'apps',
    label: 'Applications',
    sub: 'Agents, copilots, robotics, healthcare, scientific AI, industry use cases',
    desc: 'Applications are where economic value is created. This layer spans agents and copilots, code generation and search, autonomous vehicles and surgical robotics, drug discovery and climate modelling. No application exists in isolation. Each one depends on every layer beneath it, from the model it calls to the electricity that powers the data center.',
    w: 50,
  },
];

const TAX = [
  {
    cat: 'Learning paradigms',
    note: 'How models acquire knowledge, training-time decisions',
    items: [
      { n: 'Supervised learning', l: 'models' },
      { n: 'Unsupervised learning', l: 'models' },
      { n: 'Self-supervised learning', l: 'models' },
      { n: 'Reinforcement learning (model-free)', l: 'models' },
      { n: 'Reinforcement learning (model-based)', l: 'models' },
      { n: 'RLHF', l: 'models' },
      { n: 'RLAIF', l: 'models' },
      { n: 'Multi-agent RL', l: 'models' },
      { n: 'Imitation learning', l: 'models' },
      { n: 'Inverse RL', l: 'models' },
      { n: 'Continual / lifelong learning', l: 'models' },
      { n: 'Meta-learning', l: 'models' },
      { n: 'Few-shot & zero-shot learning', l: 'models' },
      { n: 'Transfer learning', l: 'models' },
      { n: 'Causal inference', l: 'models' },
      { n: 'Active learning', l: 'models' },
      { n: 'Curriculum learning', l: 'models' },
      { n: 'Test-time training', l: 'models' },
      { n: 'Synthetic data generation', l: 'models' },
    ]
  },
  {
    cat: 'Architectures',
    note: 'The structural design of models',
    items: [
      { n: 'Transformers (dense)', l: 'models' },
      { n: 'Mixture of Experts (sparse)', l: 'models' },
      { n: 'State space models (Mamba / S4)', l: 'models' },
      { n: 'RWKV', l: 'models' },
      { n: 'Vision Transformer (ViT)', l: 'models' },
      { n: 'Graph neural networks', l: 'models' },
      { n: 'Diffusion models', l: 'models' },
      { n: 'Variational autoencoders', l: 'models' },
      { n: 'GANs', l: 'models' },
      { n: 'CNNs', l: 'models' },
      { n: 'Neurosymbolic hybrids', l: 'models' },
      { n: 'Neural ODEs', l: 'models' },
      { n: 'Sparse / linear attention', l: 'models' },
      { n: 'Hypernetworks', l: 'models' },
    ]
  },
  {
    cat: 'Language & reasoning',
    note: 'LLM capabilities and inference-time techniques',
    items: [
      { n: 'Large language models (LLMs)', l: 'models' },
      { n: 'In-context learning', l: 'models' },
      { n: 'Instruction tuning', l: 'models' },
      { n: 'LoRA / parameter-efficient fine-tuning', l: 'models' },
      { n: 'Long-context modelling', l: 'models' },
      { n: 'Knowledge graphs', l: 'models' },
      { n: 'Process reward models', l: 'models' },
      { n: 'Knowledge distillation', l: 'models' },
      { n: 'Chain-of-thought prompting', l: 'apps' },
      { n: 'Tree / graph of thoughts', l: 'apps' },
      { n: 'Test-time compute scaling', l: 'apps' },
      { n: 'Retrieval-augmented generation', l: 'apps' },
      { n: 'Prompt engineering', l: 'apps' },
      { n: 'Agentic / autonomous agents', l: 'apps' },
      { n: 'Mixture of Agents', l: 'apps' },
      { n: 'Code generation', l: 'apps' },
      { n: 'Mathematical reasoning', l: 'apps' },
      { n: 'Structured output / function calling', l: 'apps' },
    ]
  },
  {
    cat: 'Vision, speech & multimodal',
    note: 'Perception across modalities',
    items: [
      { n: 'Multimodal foundation models', l: 'models' },
      { n: 'Contrastive vision-language (CLIP-style)', l: 'models' },
      { n: 'World models', l: 'models' },
      { n: 'Image classification', l: 'apps' },
      { n: 'Object detection', l: 'apps' },
      { n: 'Image segmentation', l: 'apps' },
      { n: 'Text-to-image generation', l: 'apps' },
      { n: 'Video generation', l: 'apps' },
      { n: 'Visual question answering', l: 'apps' },
      { n: '3D vision / NeRF / Gaussian splatting', l: 'apps' },
      { n: 'Dense captioning', l: 'apps' },
      { n: 'Speech recognition (ASR)', l: 'apps' },
      { n: 'Text-to-speech (TTS)', l: 'apps' },
      { n: 'Audio generation', l: 'apps' },
      { n: 'Sensor fusion', l: 'apps' },
    ]
  },
  {
    cat: 'Embodied & physical AI',
    note: 'AI that acts in the physical world',
    items: [
      { n: 'Robotic manipulation', l: 'apps' },
      { n: 'Dexterous grasping', l: 'apps' },
      { n: 'Locomotion control', l: 'apps' },
      { n: 'Sim-to-real transfer', l: 'apps' },
      { n: 'Autonomous vehicles', l: 'apps' },
      { n: 'Navigation & SLAM', l: 'apps' },
      { n: 'Human-robot interaction', l: 'apps' },
      { n: 'Whole-body control', l: 'apps' },
      { n: 'Embodied language grounding', l: 'apps' },
      { n: 'Digital twins', l: 'apps' },
      { n: 'Warehouse & industrial automation', l: 'apps' },
    ]
  },
  {
    cat: 'Alignment & safety',
    note: 'Making AI reliable, honest, and controllable',
    items: [
      { n: 'Constitutional AI', l: 'models' },
      { n: 'Mechanistic interpretability', l: 'models' },
      { n: 'Superposition & sparse autoencoders', l: 'models' },
      { n: 'Scalable oversight', l: 'models' },
      { n: 'Reward hacking / Goodhart', l: 'models' },
      { n: 'Deceptive alignment', l: 'models' },
      { n: 'Adversarial robustness', l: 'models' },
      { n: 'Bias & fairness', l: 'models' },
      { n: 'Red-teaming', l: 'models' },
      { n: 'Safety evaluations', l: 'models' },
      { n: 'Differential privacy', l: 'infra' },
      { n: 'Watermarking & provenance', l: 'apps' },
      { n: 'Hallucination detection', l: 'apps' },
      { n: 'AI governance & policy', l: 'apps' },
      { n: 'AI regulation & standards', l: 'apps' },
    ]
  },
  {
    cat: 'Systems & efficiency',
    note: 'Making AI fast, small, and scalable to deploy',
    items: [
      { n: 'Power generation & grid supply', l: 'energy' },
      { n: 'Electricity economics for AI', l: 'energy' },
      { n: 'Energy conversion efficiency', l: 'energy' },
      { n: 'Hard power constraints on scaling', l: 'energy' },
      { n: 'Renewable integration for compute', l: 'energy' },
      { n: 'GPU architecture & HBM memory', l: 'chips' },
      { n: 'Custom silicon (TPU / Trainium / Inferentia)', l: 'chips' },
      { n: 'Edge AI & on-device chips', l: 'chips' },
      { n: 'Neuromorphic computing', l: 'chips' },
      { n: 'NPUs & mobile accelerators', l: 'chips' },
      { n: 'ASICs & domain-specific silicon', l: 'chips' },
      { n: 'Chip interconnects (NVLink / NVSwitch)', l: 'chips' },
      { n: 'Optical interconnects', l: 'chips' },
      { n: 'Distributed training (FSDP / ZeRO)', l: 'infra' },
      { n: 'Tensor & pipeline parallelism', l: 'infra' },
      { n: 'Flash Attention (IO-aware ops)', l: 'infra' },
      { n: 'ML compilers (Triton / XLA / TorchDynamo)', l: 'infra' },
      { n: 'Inference serving (vLLM / TensorRT)', l: 'infra' },
      { n: 'Quantization (INT4 / INT8 / GPTQ)', l: 'infra' },
      { n: 'Speculative decoding', l: 'infra' },
      { n: 'Pruning & structured sparsity', l: 'infra' },
      { n: 'MLOps & experiment tracking', l: 'infra' },
      { n: 'Data pipeline & curation infra', l: 'infra' },
      { n: 'Federated learning', l: 'infra' },
      { n: 'CUDA & GPU software stacks', l: 'infra' },
      { n: 'Storage & networking', l: 'infra' },
      { n: 'Orchestration & scheduling', l: 'infra' },
      { n: 'Cooling & thermal management', l: 'infra' },
      { n: 'Power delivery systems', l: 'infra' },
      { n: 'Neural architecture search', l: 'models' },
      { n: 'Model merging & weight averaging', l: 'models' },
    ]
  },
  {
    cat: 'Scientific & domain AI',
    note: 'AI applied to specific high-impact fields',
    items: [
      { n: 'Protein structure prediction', l: 'apps' },
      { n: 'Generative drug discovery', l: 'apps' },
      { n: 'Genomics & bioinformatics', l: 'apps' },
      { n: 'Materials science AI', l: 'apps' },
      { n: 'Medical imaging & diagnostics', l: 'apps' },
      { n: 'Climate & weather modelling', l: 'apps' },
      { n: 'Scientific simulation', l: 'apps' },
      { n: 'Financial modelling & risk', l: 'apps' },
      { n: 'Legal AI & contract analysis', l: 'apps' },
      { n: 'AI for formal mathematics', l: 'apps' },
      { n: 'Code intelligence', l: 'apps' },
      { n: 'Education & tutoring AI', l: 'apps' },
    ]
  },
];
