/* ============================================
   AI MAP - Layer & Taxonomy Data
   ============================================ */

var LAYERS = [
  {
    id: 'energy',
    label: 'Energy',
    sub: 'Power generation, grid supply, electricity economics',
    desc: 'Every AI system begins with electricity. You cannot generate intelligence without generating power first. The energy layer is the hard floor. It determines how much compute a country, a company, or a data center can sustain. Progress here is measured in gigawatts secured, not algorithms written.',
    w: 100,
  },
  {
    id: 'chips',
    label: 'Chips',
    sub: 'GPUs, TPUs, ASICs, memory, interconnects',
    desc: 'Chips convert energy into computation. AI workloads require massive parallelism, high-bandwidth memory, and fast interconnects, a fundamentally different design point from general-purpose CPUs. The economics of intelligence are set at the silicon level: who has the chips controls the throughput.',
    w: 88,
  },
  {
    id: 'infra',
    label: 'Infrastructure',
    sub: 'CUDA, distributed systems, serving, MLOps, AI factories',
    desc: 'Infrastructure turns hardware into production capacity. This layer covers everything from CUDA and compiler stacks to distributed training frameworks, inference engines, and the orchestration systems that keep clusters running. AI factories belong here: the physical and software systems that turn racks of GPUs into reliable intelligence production.',
    w: 74,
  },
  {
    id: 'models',
    label: 'Models',
    sub: 'Architectures, learning paradigms, alignment, multimodal, world models',
    desc: 'Models are the intelligence layer. Not just large language models, but the full range of architectures and training methods that turn data into capability. This includes transformers, diffusion models, reinforcement learning, multimodal systems, world models, and the alignment research that keeps them reliable. The diversity here matters: language is one modality among many.',
    w: 62,
  },
  {
    id: 'apps',
    label: 'Applications',
    sub: 'Agents, copilots, robotics, healthcare, scientific AI, industry use cases',
    desc: 'Applications are where economic value is created. This layer spans agents and copilots, code generation and search, autonomous vehicles and surgical robotics, drug discovery and climate modelling. No application exists in isolation. Each one depends on every layer beneath it, from the model it calls to the electricity that powers the data center.',
    w: 50,
  },
];

var TAX = [
  {
    cat: 'Learning paradigms',
    note: 'How models acquire knowledge, training-time decisions',
    items: [
      { n: 'Supervised learning', l: 'models', t: 'Training on labeled input-output pairs to learn a mapping function.' },
      { n: 'Unsupervised learning', l: 'models', t: 'Finding structure in unlabeled data without explicit target signals.' },
      { n: 'Self-supervised learning', l: 'models', t: 'Generating supervisory signals from the data itself, e.g. masked token prediction.' },
      { n: 'Reinforcement learning (model-free)', l: 'models', t: 'Learning policies directly from environment rewards without building a world model.' },
      { n: 'Reinforcement learning (model-based)', l: 'models', t: 'Learning a model of the environment to plan actions and improve sample efficiency.' },
      { n: 'RLHF', l: 'models', t: 'Fine-tuning models using a reward signal derived from human preference judgments.' },
      { n: 'RLAIF', l: 'models', t: 'Replacing human labelers with AI-generated preference feedback for reward modeling.' },
      { n: 'Multi-agent RL', l: 'models', t: 'Multiple agents learning simultaneously in a shared environment with interacting policies.' },
      { n: 'Imitation learning', l: 'models', t: 'Learning behavior by observing expert demonstrations rather than explicit rewards.' },
      { n: 'Inverse RL', l: 'models', t: 'Inferring the reward function an agent is optimizing from observed behavior.' },
      { n: 'Continual / lifelong learning', l: 'models', t: 'Learning new tasks sequentially without forgetting previously acquired knowledge.' },
      { n: 'Meta-learning', l: 'models', t: 'Learning to learn: acquiring inductive biases that enable fast adaptation to new tasks.' },
      { n: 'Few-shot & zero-shot learning', l: 'models', t: 'Performing tasks with very few or no training examples by leveraging prior knowledge.' },
      { n: 'Transfer learning', l: 'models', t: 'Reusing representations learned on one task to improve performance on a different task.' },
      { n: 'Causal inference', l: 'models', t: 'Modeling cause-effect relationships rather than just statistical correlations in data.' },
      { n: 'Active learning', l: 'models', t: 'Selectively querying labels for the most informative examples to reduce annotation cost.' },
      { n: 'Curriculum learning', l: 'models', t: 'Ordering training examples from easy to hard to improve convergence and final performance.' },
      { n: 'Test-time training', l: 'models', t: 'Updating model parameters on each test input to adapt to distribution shifts at inference.' },
      { n: 'Synthetic data generation', l: 'models', t: 'Creating artificial training data using models or simulations to augment real datasets.' },
    ]
  },
  {
    cat: 'Architectures',
    note: 'The structural design of models',
    items: [
      { n: 'Transformers (dense)', l: 'models', t: 'Self-attention based architecture where every token attends to all others in the sequence.' },
      { n: 'Mixture of Experts (sparse)', l: 'models', t: 'Routing each input to a subset of specialized sub-networks to scale capacity efficiently.' },
      { n: 'State space models (Mamba / S4)', l: 'models', t: 'Sequence models using structured state spaces for linear-time inference on long contexts.' },
      { n: 'RWKV', l: 'models', t: 'Linear-complexity architecture combining RNN efficiency with transformer-level parallelism.' },
      { n: 'Vision Transformer (ViT)', l: 'models', t: 'Applying transformer self-attention to image patches for visual representation learning.' },
      { n: 'Graph neural networks', l: 'models', t: 'Neural networks operating on graph-structured data by message passing between nodes.' },
      { n: 'Diffusion models', l: 'models', t: 'Generative models that learn to reverse a gradual noising process to produce samples.' },
      { n: 'Variational autoencoders', l: 'models', t: 'Latent variable models trained to encode inputs into and decode from a smooth latent space.' },
      { n: 'GANs', l: 'models', t: 'Two networks (generator and discriminator) trained adversarially to produce realistic outputs.' },
      { n: 'CNNs', l: 'models', t: 'Networks using learned convolutional filters to extract local spatial features hierarchically.' },
      { n: 'Neurosymbolic hybrids', l: 'models', t: 'Combining neural pattern recognition with symbolic reasoning for structured problem solving.' },
      { n: 'Neural ODEs', l: 'models', t: 'Modeling continuous-time dynamics by parameterizing differential equations with neural networks.' },
      { n: 'Sparse / linear attention', l: 'models', t: 'Attention variants that reduce the quadratic cost of full self-attention to sub-quadratic.' },
      { n: 'Hypernetworks', l: 'models', t: 'Networks that generate the weights of another network, enabling dynamic parameterization.' },
    ]
  },
  {
    cat: 'Language & reasoning',
    note: 'LLM capabilities and inference-time techniques',
    items: [
      { n: 'Large language models (LLMs)', l: 'models', t: 'Autoregressive models trained on large text corpora to predict and generate language.' },
      { n: 'In-context learning', l: 'models', t: 'Conditioning on examples provided in the prompt to perform tasks without weight updates.' },
      { n: 'Instruction tuning', l: 'models', t: 'Fine-tuning on instruction-response pairs so models follow natural language directives.' },
      { n: 'LoRA / parameter-efficient fine-tuning', l: 'models', t: 'Adapting large models by training only a small number of added or modified parameters.' },
      { n: 'Long-context modelling', l: 'models', t: 'Extending the effective context window to handle documents of hundreds of thousands of tokens.' },
      { n: 'Knowledge graphs', l: 'models', t: 'Structured representations of entities and relations used for reasoning and retrieval.' },
      { n: 'Process reward models', l: 'models', t: 'Scoring each intermediate reasoning step rather than only the final answer.' },
      { n: 'Knowledge distillation', l: 'models', t: 'Training a smaller student model to replicate the behavior of a larger teacher model.' },
      { n: 'Chain-of-thought prompting', l: 'apps', t: 'Eliciting step-by-step reasoning in model outputs to improve accuracy on complex tasks.' },
      { n: 'Tree / graph of thoughts', l: 'apps', t: 'Exploring branching reasoning paths and selecting the best trajectory for a problem.' },
      { n: 'Test-time compute scaling', l: 'apps', t: 'Allocating more compute at inference to improve output quality on harder problems.' },
      { n: 'Retrieval-augmented generation', l: 'apps', t: 'Grounding model responses by retrieving relevant documents from an external knowledge base.' },
      { n: 'Prompt engineering', l: 'apps', t: 'Designing input prompts to steer model behavior toward desired outputs.' },
      { n: 'Agentic / autonomous agents', l: 'apps', t: 'Systems that plan, use tools, and take multi-step actions to complete open-ended goals.' },
      { n: 'Mixture of Agents', l: 'apps', t: 'Routing queries across multiple specialized models and aggregating their outputs.' },
      { n: 'Code generation', l: 'apps', t: 'Using language models to produce, complete, or transform source code from natural language.' },
      { n: 'Mathematical reasoning', l: 'apps', t: 'Applying formal or informal math to solve quantitative problems with verified steps.' },
      { n: 'Structured output / function calling', l: 'apps', t: 'Constraining model outputs to valid schemas like JSON or invoking external tool APIs.' },
    ]
  },
  {
    cat: 'Vision, speech & multimodal',
    note: 'Perception across modalities',
    items: [
      { n: 'Multimodal foundation models', l: 'models', t: 'Single models trained jointly on text, images, audio, or video for cross-modal reasoning.' },
      { n: 'Contrastive vision-language (CLIP-style)', l: 'models', t: 'Aligning image and text embeddings in a shared space via contrastive pre-training.' },
      { n: 'World models', l: 'models', t: 'Internal simulators that predict future states of an environment from actions and observations.' },
      { n: 'Image classification', l: 'apps', t: 'Assigning categorical labels to images based on learned visual features.' },
      { n: 'Object detection', l: 'apps', t: 'Locating and classifying objects within an image using bounding boxes or keypoints.' },
      { n: 'Image segmentation', l: 'apps', t: 'Partitioning an image into regions with per-pixel or per-region class labels.' },
      { n: 'Text-to-image generation', l: 'apps', t: 'Synthesizing images from natural language descriptions using diffusion or autoregressive models.' },
      { n: 'Video generation', l: 'apps', t: 'Producing temporally coherent video sequences from text, images, or other conditioning inputs.' },
      { n: 'Visual question answering', l: 'apps', t: 'Answering natural language questions about the content of an image.' },
      { n: '3D vision / NeRF / Gaussian splatting', l: 'apps', t: 'Reconstructing 3D scenes from 2D images using neural radiance fields or point-based rendering.' },
      { n: 'Dense captioning', l: 'apps', t: 'Generating localized natural language descriptions for multiple regions within an image.' },
      { n: 'Speech recognition (ASR)', l: 'apps', t: 'Converting spoken audio into text transcriptions using acoustic and language modeling.' },
      { n: 'Text-to-speech (TTS)', l: 'apps', t: 'Generating natural-sounding speech audio from written text input.' },
      { n: 'Audio generation', l: 'apps', t: 'Synthesizing music, sound effects, or environmental audio from text or other prompts.' },
      { n: 'Sensor fusion', l: 'apps', t: 'Combining data from multiple sensor types (camera, lidar, radar) for unified perception.' },
    ]
  },
  {
    cat: 'Embodied & physical AI',
    note: 'AI that acts in the physical world',
    items: [
      { n: 'Robotic manipulation', l: 'apps', t: 'Controlling robot arms and end-effectors to interact with and move physical objects.' },
      { n: 'Dexterous grasping', l: 'apps', t: 'Fine-grained control of multi-fingered or adaptive grippers for complex object handling.' },
      { n: 'Locomotion control', l: 'apps', t: 'Policies for stable and agile movement of legged, wheeled, or aerial robots.' },
      { n: 'Sim-to-real transfer', l: 'apps', t: 'Training policies in simulation and deploying them on physical hardware with domain adaptation.' },
      { n: 'Autonomous vehicles', l: 'apps', t: 'Self-driving systems combining perception, planning, and control for road navigation.' },
      { n: 'Navigation & SLAM', l: 'apps', t: 'Simultaneous localization and mapping for robot positioning in unknown environments.' },
      { n: 'Human-robot interaction', l: 'apps', t: 'Designing interfaces and behaviors for safe, intuitive collaboration between humans and robots.' },
      { n: 'Whole-body control', l: 'apps', t: 'Coordinating all joints and actuators of a humanoid or complex robot simultaneously.' },
      { n: 'Embodied language grounding', l: 'apps', t: 'Connecting language instructions to physical actions and spatial understanding in real scenes.' },
      { n: 'Digital twins', l: 'apps', t: 'Virtual replicas of physical systems used for simulation, monitoring, and optimization.' },
      { n: 'Warehouse & industrial automation', l: 'apps', t: 'Robotic systems for picking, packing, sorting, and material handling in logistics facilities.' },
    ]
  },
  {
    cat: 'Alignment & safety',
    note: 'Making AI reliable, honest, and controllable',
    items: [
      { n: 'Constitutional AI', l: 'models', t: 'Self-supervised alignment where models critique and revise outputs against a set of principles.' },
      { n: 'Mechanistic interpretability', l: 'models', t: 'Reverse-engineering the internal computations of neural networks into human-readable circuits.' },
      { n: 'Superposition & sparse autoencoders', l: 'models', t: 'Decomposing polysemantic neurons into interpretable features using learned sparse dictionaries.' },
      { n: 'Scalable oversight', l: 'models', t: 'Methods for humans to supervise AI systems whose capabilities exceed the evaluator.' },
      { n: 'Reward hacking / Goodhart', l: 'models', t: 'When optimizing a proxy reward leads to behavior that diverges from the intended objective.' },
      { n: 'Deceptive alignment', l: 'models', t: 'Risk that a model appears aligned during training but pursues different goals at deployment.' },
      { n: 'Adversarial robustness', l: 'models', t: 'Maintaining correct behavior under intentionally crafted adversarial inputs or perturbations.' },
      { n: 'Bias & fairness', l: 'models', t: 'Identifying and mitigating systematic disparities in model predictions across demographic groups.' },
      { n: 'Red-teaming', l: 'models', t: 'Probing models with adversarial prompts and scenarios to discover failure modes and risks.' },
      { n: 'Safety evaluations', l: 'models', t: 'Systematic benchmarks and tests measuring dangerous capabilities or alignment failures.' },
      { n: 'Differential privacy', l: 'infra', t: 'Mathematical framework bounding how much any individual training example influences model output.' },
      { n: 'Watermarking & provenance', l: 'apps', t: 'Embedding detectable signals in AI outputs to trace origin and verify authenticity.' },
      { n: 'Hallucination detection', l: 'apps', t: 'Identifying when a model generates claims not grounded in its source data or context.' },
      { n: 'AI governance & policy', l: 'apps', t: 'Organizational and governmental frameworks for responsible AI development and deployment.' },
      { n: 'AI regulation & standards', l: 'apps', t: 'Legal requirements and technical standards governing AI system safety and accountability.' },
    ]
  },
  {
    cat: 'Systems & efficiency',
    note: 'Making AI fast, small, and scalable to deploy',
    items: [
      { n: 'Power generation & grid supply', l: 'energy', tab: 'world',       t: 'Sourcing and delivering electricity at the scale required for large AI data centers. Click for the global dashboard.' },
      { n: 'Electricity economics for AI',   l: 'energy', tab: 'compute',     t: 'Cost structures, pricing models, and contracts that determine the price per compute-hour. Click for the AI-compute economics deep-dive.' },
      { n: 'Energy conversion efficiency',   l: 'energy', tab: 'compute',     t: 'Ratio of useful computational work to total electrical energy consumed by a facility. Click for the PUE + calculator section.' },
      { n: 'Hard power constraints on scaling', l: 'energy', tab: 'constraints', t: 'Physical limits on available power that cap the size and throughput of training runs. Click for the constraints checklist.' },
      { n: 'Renewable integration for compute', l: 'energy', tab: 'compute',     t: 'Using solar, wind, and other renewables to power AI workloads with lower carbon intensity. Click for the renewable-integration deep-dive.' },
      { n: 'GPU architecture & HBM memory', l: 'chips', t: 'Massively parallel processor designs paired with high-bandwidth stacked memory for AI workloads.' },
      { n: 'Custom silicon (TPU / Trainium / Inferentia)', l: 'chips', t: 'Purpose-built accelerators designed by cloud providers for specific training or inference tasks.' },
      { n: 'Edge AI & on-device chips', l: 'chips', t: 'Low-power processors that run inference locally on phones, cameras, or embedded devices.' },
      { n: 'Neuromorphic computing', l: 'chips', t: 'Brain-inspired chip architectures using spiking neurons and event-driven computation.' },
      { n: 'NPUs & mobile accelerators', l: 'chips', t: 'Dedicated neural processing units integrated into mobile SoCs for on-device AI tasks.' },
      { n: 'ASICs & domain-specific silicon', l: 'chips', t: 'Fixed-function chips optimized for a narrow set of operations like matrix multiplication.' },
      { n: 'Chip interconnects (NVLink / NVSwitch)', l: 'chips', t: 'High-bandwidth links between GPUs enabling fast data exchange within multi-chip systems.' },
      { n: 'Optical interconnects', l: 'chips', t: 'Using light-based signaling to increase bandwidth and reduce power in chip-to-chip communication.' },
      { n: 'Distributed training (FSDP / ZeRO)', l: 'infra', t: 'Sharding model state across many GPUs to train models that exceed single-device memory.' },
      { n: 'Tensor & pipeline parallelism', l: 'infra', t: 'Splitting model layers or operations across devices to parallelize forward and backward passes.' },
      { n: 'Flash Attention (IO-aware ops)', l: 'infra', t: 'Memory-efficient attention that minimizes HBM reads/writes by fusing operations in SRAM.' },
      { n: 'ML compilers (Triton / XLA / TorchDynamo)', l: 'infra', t: 'Compilers that lower model graphs into optimized GPU kernels for faster execution.' },
      { n: 'Inference serving (vLLM / TensorRT)', l: 'infra', t: 'Systems for batching, scheduling, and serving model predictions at low latency and high throughput.' },
      { n: 'Quantization (INT4 / INT8 / GPTQ)', l: 'infra', t: 'Reducing weight and activation precision to shrink model size and speed up inference.' },
      { n: 'Speculative decoding', l: 'infra', t: 'Using a small draft model to propose tokens verified in parallel by the large model.' },
      { n: 'Pruning & structured sparsity', l: 'infra', t: 'Removing redundant weights or channels to reduce compute with minimal accuracy loss.' },
      { n: 'MLOps & experiment tracking', l: 'infra', t: 'Tooling for versioning data, tracking runs, and managing the model development lifecycle.' },
      { n: 'Data pipeline & curation infra', l: 'infra', t: 'Systems for collecting, cleaning, filtering, and deduplicating training datasets at scale.' },
      { n: 'Federated learning', l: 'infra', t: 'Training models across decentralized devices without centralizing raw user data.' },
      { n: 'CUDA & GPU software stacks', l: 'infra', t: 'Programming frameworks and libraries that expose GPU parallelism for AI workloads.' },
      { n: 'Storage & networking', l: 'infra', t: 'High-throughput storage and low-latency networks connecting compute nodes in AI clusters.' },
      { n: 'Orchestration & scheduling', l: 'infra', t: 'Resource managers that allocate GPU clusters and schedule training and inference jobs.' },
      { n: 'Cooling & thermal management', l: 'infra', t: 'Liquid and air cooling systems that remove waste heat to maintain chip reliability.' },
      { n: 'Power delivery systems', l: 'infra', t: 'Electrical infrastructure converting and distributing power from grid to rack-level components.' },
      { n: 'Neural architecture search', l: 'models', t: 'Automated methods for discovering optimal model architectures given compute and task constraints.' },
      { n: 'Model merging & weight averaging', l: 'models', t: 'Combining weights from separately trained models to blend capabilities without retraining.' },
    ]
  },
  {
    cat: 'Scientific & domain AI',
    note: 'AI applied to specific high-impact fields',
    items: [
      { n: 'Protein structure prediction', l: 'apps', t: 'Predicting 3D protein folding from amino acid sequences using learned structural priors.' },
      { n: 'Generative drug discovery', l: 'apps', t: 'Designing novel molecular candidates with desired properties using generative models.' },
      { n: 'Genomics & bioinformatics', l: 'apps', t: 'Analyzing DNA, RNA, and protein sequences to understand biological function and variation.' },
      { n: 'Materials science AI', l: 'apps', t: 'Accelerating discovery of new materials by predicting properties from composition and structure.' },
      { n: 'Medical imaging & diagnostics', l: 'apps', t: 'Automated analysis of scans (X-ray, MRI, CT) to detect and classify pathologies.' },
      { n: 'Climate & weather modelling', l: 'apps', t: 'ML-based forecasting systems for weather prediction and long-range climate simulation.' },
      { n: 'Scientific simulation', l: 'apps', t: 'Replacing or augmenting physics simulators with neural surrogates for faster computation.' },
      { n: 'Financial modelling & risk', l: 'apps', t: 'Using ML for pricing, portfolio optimization, fraud detection, and risk quantification.' },
      { n: 'Legal AI & contract analysis', l: 'apps', t: 'Automated extraction, review, and summarization of clauses and obligations in legal documents.' },
      { n: 'AI for formal mathematics', l: 'apps', t: 'Assisting with theorem proving and formalization in proof assistants like Lean or Coq.' },
      { n: 'Code intelligence', l: 'apps', t: 'Semantic understanding of codebases for search, refactoring, bug detection, and review.' },
      { n: 'Education & tutoring AI', l: 'apps', t: 'Personalized learning systems that adapt explanations and exercises to individual student needs.' },
    ]
  },
];
