// ============================================
// The AI Atlas — Paper Data
// 50 Papers That Built Modern AI
// ============================================

const ATLAS_DATA = {

  eras: [
    { id: 1, name: "Foundations", period: "Pre-2012", color: "#ff6b6b", desc: "The building blocks that made everything possible." },
    { id: 2, name: "Deep Learning Revolution", period: "2012-2016", color: "#ffa500", desc: "Deep learning goes from academic curiosity to world-changing technology." },
    { id: 3, name: "The Transformer Era", period: "2017-2019", color: "#4ecdc4", desc: "The architecture that ate AI." },
    { id: 4, name: "The LLM Age", period: "2020-2022", color: "#a855f7", desc: "Scale changes everything. Emergent abilities appear. AI enters the mainstream." },
    { id: 5, name: "The Frontier", period: "2023-2025", color: "#22c55e", desc: "Efficiency, multimodality, open-source, and reasoning at the cutting edge." }
  ],

  paths: [
    {
      id: 1,
      name: "NLP / LLM Track",
      icon: "\u{1F4AC}",
      desc: "From word vectors to reasoning models",
      papers: [12, 10, 11, 20, 21, 23, 24, 25, 37, 38]
    },
    {
      id: 2,
      name: "Computer Vision Track",
      icon: "\u{1F441}",
      desc: "From LeNet to vision-language models",
      papers: [5, 8, 9, 17, 26, 28, 29, 34]
    },
    {
      id: 3,
      name: "Generative AI Track",
      icon: "\u{1F3A8}",
      desc: "From GANs to Stable Diffusion",
      papers: [13, 14, 30, 33, 34, 35, 29]
    },
    {
      id: 4,
      name: "Foundations Track",
      icon: "\u{1F9F1}",
      desc: "The bedrock of deep learning",
      papers: [1, 2, 3, 6, 18, 7, 17, 20]
    },
    {
      id: 5,
      name: "RL & Decision Making",
      icon: "\u{1F3AE}",
      desc: "From Q-learning to RLHF",
      papers: [15, 16, 37, 45]
    },
    {
      id: 6,
      name: "Scaling & Efficiency",
      icon: "\u{26A1}",
      desc: "Making large models practical",
      papers: [25, 36, 40, 41, 44, 42]
    },
    {
      id: 7,
      name: "Multimodal & Retrieval",
      icon: "\u{1F310}",
      desc: "Connecting vision, language, and knowledge",
      papers: [12, 29, 28, 35, 32, 48, 46, 50]
    }
  ],

  featuredIds: [1, 2, 5, 11, 13, 17, 20, 24, 29, 37],

  papers: [
    // ========== ERA 1: FOUNDATIONS ==========
    {
      id: 1,
      title: "The Perceptron: A Probabilistic Model for Information Storage and Organization in the Brain",
      shortTitle: "Perceptron",
      authors: "Frank Rosenblatt",
      year: 1958,
      venue: "Psychological Review",
      era: 1,
      impact: 3,
      oneLiner: "The original artificial neuron \u2014 the atomic unit of every neural network that followed.",
      problem: "No mathematical model existed for how a machine could learn from data. Pattern recognition was done with hand-crafted rules.",
      insight: "A single computing unit can learn to classify inputs by adjusting weights based on errors. The perceptron learning rule \u2014 multiply inputs by weights, sum them, and threshold \u2014 is embarrassingly simple, yet it proved machines could learn.",
      holds: "The core idea of weighted sum + activation is literally what every neuron in every neural network does today. The learning-by-error-correction principle became backpropagation.",
      superseded: "Single-layer perceptrons can't learn XOR or any non-linearly-separable function \u2014 Minsky & Papert proved this in 1969 and nearly killed the field for a decade.",
      practitioner: "You'll never use a perceptron directly, but understanding it makes everything else click \u2014 it's the \"Hello World\" of neural networks.",
      tags: ["foundations", "neural-networks", "classification"],
      deps: [],
      unlocks: [2, 3],
      link: "https://psycnet.apa.org/record/1959-09865-001"
    },
    {
      id: 2,
      title: "Learning Representations by Back-Propagating Errors",
      shortTitle: "Backpropagation",
      authors: "David Rumelhart, Geoffrey Hinton, Ronald Williams",
      year: 1986,
      venue: "Nature",
      era: 1,
      impact: 3,
      oneLiner: "The algorithm that taught neural networks how to learn \u2014 backpropagation made deep learning possible.",
      problem: "Multi-layer networks existed but nobody knew how to train them effectively. Credit assignment \u2014 figuring out which weights to blame for errors \u2014 was unsolved.",
      insight: "Use the chain rule of calculus to propagate error gradients backward through every layer. Each weight gets a gradient telling it exactly how much (and in which direction) to change. Simple, elegant, and it scales to arbitrary depth.",
      holds: "Every neural network you've ever used \u2014 GPT-4, Stable Diffusion, AlphaFold \u2014 is trained with backpropagation. It's the single most important algorithm in deep learning.",
      superseded: "The original formulation used sigmoid activations which suffer from vanishing gradients. Modern networks use ReLU, skip connections, and normalization to fix this.",
      practitioner: "If you understand backprop deeply \u2014 how gradients flow, where they vanish or explode \u2014 you can debug almost any training issue. This is THE foundational skill.",
      tags: ["foundations", "optimization", "training"],
      deps: [1],
      unlocks: [3, 4, 5, 6, 7, 8, 12, 13, 14, 15, 16, 18],
      link: "https://www.nature.com/articles/323533a0"
    },
    {
      id: 3,
      title: "Approximation by Superpositions of a Sigmoidal Function",
      shortTitle: "Universal Approx.",
      authors: "George Cybenko",
      year: 1989,
      venue: "Mathematics of Control, Signals and Systems",
      era: 1,
      impact: 2,
      oneLiner: "A neural network with one hidden layer can approximate ANY continuous function \u2014 the theoretical green light for deep learning.",
      problem: "People questioned whether neural networks were fundamentally limited. Could they actually represent complex real-world functions, or were they just toys?",
      insight: "A feedforward network with a single hidden layer containing a finite number of neurons can approximate any continuous function on compact subsets of R\u207F, to any desired accuracy. Neural networks are universal function approximators.",
      holds: "The theorem remains true and is the theoretical justification for why neural networks work. It's why we trust them with everything from language to protein folding.",
      superseded: "The theorem says a wide-enough single layer works in theory, but practice showed depth matters more than width. Deep networks are exponentially more efficient than wide shallow ones.",
      practitioner: "This is why neural networks can learn anything \u2014 but the theorem says nothing about HOW to learn it. That's where architecture design, training tricks, and data come in.",
      tags: ["foundations", "theory", "approximation"],
      deps: [1, 2],
      unlocks: [6, 13],
      link: "https://doi.org/10.1007/BF02551274"
    },
    {
      id: 4,
      title: "Long Short-Term Memory",
      shortTitle: "LSTM",
      authors: "Sepp Hochreiter, J\u00FCrgen Schmidhuber",
      year: 1997,
      venue: "Neural Computation",
      era: 1,
      impact: 3,
      oneLiner: "The memory architecture that let neural networks finally handle sequences \u2014 from speech to text to time series.",
      problem: "Standard RNNs suffered from vanishing/exploding gradients \u2014 they'd forget information after ~10-20 time steps. Long-range dependencies were impossible to learn.",
      insight: "Add a \"memory cell\" with three gates (input, forget, output) that control information flow. The cell state acts like a conveyor belt \u2014 information can flow through unchanged, or be selectively updated. Gradients can flow through the cell unimpeded.",
      holds: "The gating mechanism concept directly inspired the Transformer's residual connections. LSTM is still used in some production systems for time series and edge deployment.",
      superseded: "Transformers largely replaced LSTMs for NLP (2017+). Self-attention handles long-range dependencies better and enables parallelization. GRU simplified the gating mechanism.",
      practitioner: "LSTMs taught the field how to solve vanishing gradients through gating. If you work with sequential data on resource-constrained devices, LSTMs still have a place.",
      tags: ["foundations", "sequence-modeling", "rnn", "gating"],
      deps: [2],
      unlocks: [10, 11],
      link: "https://doi.org/10.1162/neco.1997.9.8.1735"
    },
    {
      id: 5,
      title: "Gradient-Based Learning Applied to Document Recognition",
      shortTitle: "LeNet / CNN",
      authors: "Yann LeCun, L\u00E9on Bottou, Yoshua Bengio, Patrick Haffner",
      year: 1998,
      venue: "Proceedings of the IEEE",
      era: 1,
      impact: 3,
      oneLiner: "The birth of convolutional neural networks \u2014 LeNet proved that learned features beat hand-crafted ones for vision.",
      problem: "Computer vision relied on hand-engineered feature extractors (SIFT, HOG, etc.). These were brittle, task-specific, and couldn't scale.",
      insight: "Use convolutions \u2014 small learnable filters that slide across the image \u2014 to automatically discover relevant visual features. Pooling layers add translation invariance. The whole pipeline is end-to-end trainable with backprop.",
      holds: "Convolutions are still everywhere \u2014 even Vision Transformers use patch embeddings that are essentially convolutions. The idea of hierarchical feature learning (edges \u2192 textures \u2192 parts \u2192 objects) remains the paradigm.",
      superseded: "LeNet's specific architecture (5 layers, tanh activations) is tiny by modern standards. Vision Transformers have shown convolutions aren't strictly necessary at scale.",
      practitioner: "CNNs are still the default for efficient vision on edge devices. Understanding receptive fields and feature hierarchies is essential for any vision work.",
      tags: ["foundations", "computer-vision", "cnn", "feature-learning"],
      deps: [2],
      unlocks: [8, 9, 15, 17, 18, 19, 26, 27],
      link: "http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf"
    },
    {
      id: 6,
      title: "Dropout: A Simple Way to Prevent Neural Networks from Overfitting",
      shortTitle: "Dropout",
      authors: "Nitish Srivastava, Geoffrey Hinton, Alex Krizhevsky, Ilya Sutskever, Ruslan Salakhutdinov",
      year: 2014,
      venue: "JMLR",
      era: 1,
      impact: 2,
      oneLiner: "Randomly turning off neurons during training creates an implicit ensemble \u2014 the simplest and most effective regularizer.",
      problem: "Deep networks were powerful but overfit badly on limited data. Ensemble methods worked but were computationally expensive (training N separate models).",
      insight: "During training, randomly zero out each neuron with probability p (typically 0.5). This forces the network to learn redundant representations \u2014 no single neuron can be relied upon. At test time, scale weights by (1-p). Effectively trains an exponential number of sub-networks.",
      holds: "Dropout is still used in many architectures, especially fully-connected layers. The concept of stochastic regularization inspired DropPath, DropBlock, and stochastic depth.",
      superseded: "For Transformers, layer normalization + weight decay + attention dropout have largely replaced traditional dropout. BatchNorm also provides implicit regularization.",
      practitioner: "If your model overfits and you're not using dropout yet, start here. It's free performance. Also useful for uncertainty estimation via MC Dropout.",
      tags: ["foundations", "regularization", "training"],
      deps: [2, 3],
      unlocks: [8],
      link: "https://jmlr.org/papers/v15/srivastava14a.html"
    },
    {
      id: 7,
      title: "Adam: A Method for Stochastic Optimization",
      shortTitle: "Adam",
      authors: "Diederik Kingma, Jimmy Ba",
      year: 2015,
      venue: "ICLR",
      era: 1,
      impact: 3,
      oneLiner: "The optimizer that just works \u2014 Adam combines momentum and adaptive learning rates and became the default for training deep networks.",
      problem: "SGD with momentum worked but required careful learning rate tuning. Adagrad decayed learning rates too aggressively. Different parameters needed different learning rates.",
      insight: "Maintain running averages of both the gradient (first moment) and the squared gradient (second moment). Use these to adaptively scale the learning rate per parameter. Bias correction handles initialization. Result: fast convergence with minimal hyperparameter tuning.",
      holds: "Adam (and AdamW with decoupled weight decay) is the default optimizer for training Transformers, LLMs, and most deep learning models. You'll use it in nearly every project.",
      superseded: "For some tasks (e.g., ImageNet training), SGD with momentum + cosine scheduling still wins. AdamW fixed a subtle bug in Adam's weight decay implementation.",
      practitioner: "Just use AdamW with a cosine learning rate schedule and warmup. This combo works for 90% of deep learning tasks. Only experiment with other optimizers if you have a specific reason.",
      tags: ["foundations", "optimization", "training"],
      deps: [2],
      unlocks: [14, 20],
      link: "https://arxiv.org/abs/1412.6980"
    },

    // ========== ERA 2: DEEP LEARNING REVOLUTION ==========
    {
      id: 8,
      title: "ImageNet Classification with Deep Convolutional Neural Networks",
      shortTitle: "AlexNet",
      authors: "Alex Krizhevsky, Ilya Sutskever, Geoffrey Hinton",
      year: 2012,
      venue: "NeurIPS",
      era: 2,
      impact: 3,
      oneLiner: "The paper that launched the deep learning revolution \u2014 AlexNet crushed ImageNet and proved deep CNNs work at scale.",
      problem: "Computer vision competitions were dominated by hand-engineered features + SVMs. Progress had plateaued. The 2011 ImageNet winner had 25.8% top-5 error.",
      insight: "Train a deep CNN (8 layers, 60M parameters) on ImageNet using two GPUs, ReLU activations, dropout, and data augmentation. Achieved 15.3% top-5 error \u2014 absolutely demolished the competition (26.2% for second place). The gap was unprecedented.",
      holds: "ReLU activation, data augmentation, GPU training, and dropout are all still standard. The insight that more data + more compute + deep networks = better performance is the entire basis of modern AI.",
      superseded: "The architecture itself is completely outdated. No one uses AlexNet. Local response normalization was replaced by batch/layer norm. The 2-GPU split was a hardware constraint, not a design choice.",
      practitioner: "AlexNet is why you have a job in AI. It convinced the world that deep learning works. Understanding why it worked (data + compute + architecture) is the meta-lesson.",
      tags: ["deep-learning", "computer-vision", "cnn", "gpu", "imagenet"],
      deps: [2, 5, 6],
      unlocks: [9, 17, 18, 19, 26],
      link: "https://papers.nips.cc/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html"
    },
    {
      id: 9,
      title: "Very Deep Convolutional Networks for Large-Scale Image Recognition",
      shortTitle: "VGGNet",
      authors: "Karen Simonyan, Andrew Zisserman",
      year: 2014,
      venue: "ICLR 2015",
      era: 2,
      impact: 2,
      oneLiner: "Going deeper with simple 3\u00D73 convolutions \u2014 VGGNet proved that network depth is what matters most.",
      problem: "After AlexNet, it was unclear whether to go wider (more filters) or deeper (more layers). Architecture design was ad hoc.",
      insight: "Use a uniform architecture of stacked 3\u00D73 convolution layers (the smallest size that captures spatial patterns). Two 3\u00D73 layers have the same receptive field as one 5\u00D75 but with fewer parameters and more non-linearity. Go 16-19 layers deep.",
      holds: "The principle of using small, stacked filters instead of large ones is universal. VGG features are still used as perceptual loss functions in style transfer and super-resolution.",
      superseded: "VGGNet is extremely parameter-heavy (138M parameters) and slow. ResNet, EfficientNet, and ViT all achieve far better performance with fewer parameters.",
      practitioner: "VGG's legacy is the design principle: depth > width, and small filters > large filters. Its feature representations remain useful as a perceptual loss.",
      tags: ["deep-learning", "computer-vision", "cnn", "depth"],
      deps: [5, 8],
      unlocks: [17],
      link: "https://arxiv.org/abs/1409.1556"
    },
    {
      id: 10,
      title: "Sequence to Sequence Learning with Neural Networks",
      shortTitle: "Seq2Seq",
      authors: "Ilya Sutskever, Oriol Vinyals, Quoc Le",
      year: 2014,
      venue: "NeurIPS",
      era: 2,
      impact: 3,
      oneLiner: "Encode an entire input sequence into a fixed vector, then decode it into an output sequence \u2014 the architecture that enabled neural machine translation.",
      problem: "Machine translation used phrase-based statistical models with complex pipelines. Neural approaches couldn't handle variable-length input/output pairs.",
      insight: "Use one LSTM to encode the input sequence into a fixed-size context vector, then use another LSTM to decode this vector into the output sequence. Reversing the input sequence dramatically improved performance by creating short-term dependencies.",
      holds: "The encoder-decoder paradigm is the foundation of most seq2seq systems. T5, BART, and many production translation systems still use this pattern.",
      superseded: "The fixed-size bottleneck vector was the critical limitation \u2014 it couldn't scale to long sequences. Attention mechanisms (Bahdanau 2015) solved this by letting the decoder look at all encoder states.",
      practitioner: "If you're building any system that maps one sequence to another (translation, summarization, code generation), you're using a descendant of this architecture.",
      tags: ["deep-learning", "nlp", "sequence-modeling", "encoder-decoder", "translation"],
      deps: [4],
      unlocks: [11],
      link: "https://arxiv.org/abs/1409.3215"
    },
    {
      id: 11,
      title: "Neural Machine Translation by Jointly Learning to Align and Translate",
      shortTitle: "Attention",
      authors: "Dzmitry Bahdanau, KyungHyun Cho, Yoshua Bengio",
      year: 2015,
      venue: "ICLR",
      era: 2,
      impact: 3,
      oneLiner: "Instead of compressing everything into one vector, let the decoder attend to relevant parts of the input \u2014 the attention mechanism that changed everything.",
      problem: "Seq2seq models compressed entire inputs into a single fixed-size vector. Long sentences lost critical information. Translation quality degraded badly on long inputs.",
      insight: "At each decoding step, compute a weighted combination of ALL encoder hidden states, where the weights (attention scores) indicate which input positions are most relevant. The decoder dynamically focuses on different parts of the input for each output token.",
      holds: "Attention is THE fundamental mechanism in modern AI. Every Transformer, every LLM, every vision model uses attention. This paper literally created the building block of the current AI era.",
      superseded: "The original additive attention was replaced by dot-product attention (more efficient) in the Transformer. The RNN encoder/decoder was replaced by pure self-attention.",
      practitioner: "Understanding attention \u2014 how queries match keys to aggregate values \u2014 is non-negotiable for any AI practitioner. If you deeply understand attention, you understand 80% of how LLMs work.",
      tags: ["deep-learning", "nlp", "attention", "translation"],
      deps: [4, 10],
      unlocks: [20],
      link: "https://arxiv.org/abs/1409.0473"
    },
    {
      id: 12,
      title: "Efficient Estimation of Word Representations in Vector Space",
      shortTitle: "Word2Vec",
      authors: "Tomas Mikolov, Kai Chen, Greg Corrado, Jeffrey Dean",
      year: 2013,
      venue: "ICLR Workshop",
      era: 2,
      impact: 3,
      oneLiner: "Words as vectors \u2014 Word2Vec proved that distributional semantics create meaningful geometry where \"king - man + woman = queen.\"",
      problem: "Words were represented as one-hot vectors \u2014 no notion of similarity. \"cat\" and \"dog\" were as different as \"cat\" and \"quantum.\" Semantic relationships couldn't be captured.",
      insight: "Train a shallow neural network to predict a word from its context (CBOW) or context from a word (Skip-gram). The hidden layer weights become dense vector representations that capture semantic meaning. Similar words get similar vectors. Vector arithmetic captures analogies.",
      holds: "The distributional hypothesis (\"you shall know a word by the company it keeps\") is the foundation of ALL language models including GPT-4. Embeddings are everywhere.",
      superseded: "Static embeddings (one vector per word regardless of context) were replaced by contextual embeddings (ELMo, BERT, GPT). Subword tokenization (BPE) replaced word-level tokens.",
      practitioner: "Word2Vec is the conceptual foundation for understanding why LLMs work. Token embeddings in Transformers are a direct descendant. If you get Word2Vec, you get the \"why\" behind language models.",
      tags: ["deep-learning", "nlp", "embeddings", "representation-learning"],
      deps: [2],
      unlocks: [20, 21, 22],
      link: "https://arxiv.org/abs/1301.3781"
    },
    {
      id: 13,
      title: "Generative Adversarial Networks",
      shortTitle: "GANs",
      authors: "Ian Goodfellow, Jean Pouget-Abadie, Mehdi Mirza, Bing Xu, David Warde-Farley, Sherjil Ozair, Aaron Courville, Yoshua Bengio",
      year: 2014,
      venue: "NeurIPS",
      era: 2,
      impact: 3,
      oneLiner: "Two networks in a game \u2014 a generator that creates fakes and a discriminator that catches them \u2014 competing until the fakes become indistinguishable from real.",
      problem: "Generative models (VAEs, RBMs) produced blurry outputs. There was no good way to generate sharp, realistic images from neural networks.",
      insight: "Frame generation as a minimax game. The generator tries to produce samples that fool the discriminator; the discriminator tries to tell real from fake. At Nash equilibrium, the generator produces samples from the true data distribution. No explicit density estimation needed.",
      holds: "The adversarial training concept influenced discriminator-guided diffusion, domain adaptation, and data augmentation. StyleGAN still produces some of the best face images.",
      superseded: "GANs are notoriously hard to train (mode collapse, training instability). Diffusion models have largely replaced GANs for image generation \u2014 they're more stable and produce more diverse outputs.",
      practitioner: "GANs were the generative AI revolution before diffusion models. Understanding them helps you appreciate why diffusion models won (stability + diversity > raw sharpness).",
      tags: ["deep-learning", "generative", "adversarial", "image-generation"],
      deps: [2, 3],
      unlocks: [30],
      link: "https://arxiv.org/abs/1406.2661"
    },
    {
      id: 14,
      title: "Auto-Encoding Variational Bayes",
      shortTitle: "VAE",
      authors: "Diederik Kingma, Max Welling",
      year: 2014,
      venue: "ICLR",
      era: 2,
      impact: 3,
      oneLiner: "Learn a smooth, structured latent space where you can generate new data by sampling \u2014 the probabilistic foundation for generative models.",
      problem: "Autoencoders could compress and reconstruct data, but their latent spaces were unstructured \u2014 you couldn't meaningfully sample from them to generate new data.",
      insight: "Add a probabilistic twist: the encoder outputs a distribution (mean + variance), not a point. Regularize this distribution to be close to a standard normal using KL divergence. The \"reparameterization trick\" makes this differentiable. Result: a smooth latent space you can actually sample from.",
      holds: "VAEs are foundational to latent diffusion models (Stable Diffusion uses a VAE encoder/decoder). The concept of learned latent spaces is central to modern generative AI.",
      superseded: "Pure VAEs produce blurry outputs compared to GANs and diffusion models. The reconstruction loss (usually MSE) doesn't capture perceptual quality well.",
      practitioner: "If you use Stable Diffusion, you're using a VAE. Understanding latent spaces \u2014 encoding data into a compressed, meaningful representation \u2014 is critical for modern generative AI.",
      tags: ["deep-learning", "generative", "latent-space", "probabilistic"],
      deps: [2, 7],
      unlocks: [33, 34],
      link: "https://arxiv.org/abs/1312.6114"
    },
    {
      id: 15,
      title: "Playing Atari with Deep Reinforcement Learning",
      shortTitle: "DQN",
      authors: "Volodymyr Mnih, Koray Kavukcuoglu, David Silver, et al.",
      year: 2013,
      venue: "NeurIPS Workshop / Nature",
      era: 2,
      impact: 2,
      oneLiner: "A CNN that learns to play Atari games from raw pixels better than humans \u2014 deep reinforcement learning was born.",
      problem: "RL worked on small, discrete problems but couldn't handle high-dimensional inputs like raw images. Function approximation with neural networks was unstable.",
      insight: "Use a CNN to approximate the Q-function (expected future reward) directly from game pixels. Two key tricks: experience replay (store transitions, sample randomly to break correlations) and a target network (separate, slowly-updated copy to stabilize training).",
      holds: "Experience replay and target networks are still standard in deep RL. The idea of end-to-end learning from pixels to actions is the foundation of robot learning.",
      superseded: "DQN only works for discrete action spaces. Policy gradient methods (PPO) handle continuous actions. Model-based RL is more sample-efficient.",
      practitioner: "DQN proved neural networks + RL works. The experience replay concept shows up everywhere \u2014 even in offline RL and replay buffers for continual learning.",
      tags: ["deep-learning", "reinforcement-learning", "cnn", "games"],
      deps: [2, 5],
      unlocks: [16, 37],
      link: "https://arxiv.org/abs/1312.5602"
    },
    {
      id: 16,
      title: "Mastering the Game of Go with Deep Neural Networks and Tree Search",
      shortTitle: "AlphaGo",
      authors: "David Silver, Aja Huang, Chris Maddison, et al. (DeepMind)",
      year: 2016,
      venue: "Nature",
      era: 2,
      impact: 3,
      oneLiner: "AI defeats the world champion at Go \u2014 a game with more positions than atoms in the universe \u2014 by combining deep learning with Monte Carlo tree search.",
      problem: "Go was considered the \"grand challenge\" of game AI. Its branching factor (~250 moves per position) made brute-force search impossible. The best Go programs played at amateur level.",
      insight: "Train a policy network (which move to play) via supervised learning on human games, then improve it via self-play RL. Train a value network (who's winning) to evaluate positions. Combine both with MCTS for superhuman play.",
      holds: "The self-play paradigm (agent improves by playing itself) is used in LLM training (constitutional AI, self-play fine-tuning). The combination of learning + search is the foundation of reasoning models like o1.",
      superseded: "AlphaGo Zero eliminated the need for human game data entirely \u2014 pure self-play from random initialization. MuZero learned even without knowing the rules.",
      practitioner: "AlphaGo is why \"AI\" went mainstream. More importantly, the self-play + search paradigm is directly relevant to how reasoning LLMs work today.",
      tags: ["deep-learning", "reinforcement-learning", "games", "search", "self-play"],
      deps: [2, 15],
      unlocks: [37],
      link: "https://www.nature.com/articles/nature16961"
    },

    // ========== ERA 3: THE TRANSFORMER ERA ==========
    {
      id: 17,
      title: "Deep Residual Learning for Image Recognition",
      shortTitle: "ResNet",
      authors: "Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun",
      year: 2015,
      venue: "CVPR 2016",
      era: 2,
      impact: 3,
      oneLiner: "Skip connections solved the degradation problem and enabled training networks 100+ layers deep \u2014 the most cited paper in all of deep learning.",
      problem: "Very deep networks (20+ layers) performed WORSE than shallow ones during training. Adding layers actually hurt performance \u2014 not from overfitting, but from optimization difficulty.",
      insight: "Add \"skip connections\" (residual connections) that let the input bypass one or more layers: output = F(x) + x. Now the layers only need to learn the residual (the difference). If a layer isn't useful, it can learn F(x) = 0 and just pass the input through. This makes optimization dramatically easier.",
      holds: "Residual connections are in EVERY modern architecture \u2014 Transformers, diffusion models, LLMs. They're arguably the single most important architectural innovation in deep learning.",
      superseded: "The specific ResNet architectures (ResNet-50, -101, -152) are outdated for state-of-the-art vision. ViT and ConvNeXt offer better performance. BatchNorm has been replaced by LayerNorm in Transformers.",
      practitioner: "Residual connections are why deep learning works at depth. Every Transformer layer is a residual block. If you understand ResNet, you understand why Transformers can be 100+ layers deep.",
      tags: ["deep-learning", "computer-vision", "architecture", "residual-connections"],
      deps: [5, 8, 9, 18],
      unlocks: [20, 26, 27, 28, 29, 33],
      link: "https://arxiv.org/abs/1512.03385"
    },
    {
      id: 18,
      title: "Batch Normalization: Accelerating Deep Network Training",
      shortTitle: "BatchNorm",
      authors: "Sergey Ioffe, Christian Szegedy",
      year: 2015,
      venue: "ICML",
      era: 2,
      impact: 2,
      oneLiner: "Normalize activations within each mini-batch to stabilize and accelerate training \u2014 the trick that made deep networks practical.",
      problem: "Deep networks were sensitive to initialization and learning rates. Training was slow and unstable. Internal covariate shift was blamed.",
      insight: "For each mini-batch, normalize activations to zero mean and unit variance, then scale and shift with learned parameters. This smooths the loss landscape, allows higher learning rates, and acts as a regularizer.",
      holds: "Normalization is essential. The concept of normalizing intermediate representations is universal.",
      superseded: "BatchNorm depends on batch size and doesn't work well for sequences or small batches. LayerNorm (Transformers), GroupNorm, and RMSNorm are preferred in modern architectures.",
      practitioner: "You'll almost never use BatchNorm directly in modern work (it's LayerNorm for Transformers, GroupNorm for small-batch vision). But understanding WHY normalization helps is essential.",
      tags: ["deep-learning", "training", "normalization", "optimization"],
      deps: [2, 5, 8],
      unlocks: [17],
      link: "https://arxiv.org/abs/1502.03167"
    },
    {
      id: 19,
      title: "ImageNet Large Scale Visual Recognition Challenge",
      shortTitle: "ImageNet",
      authors: "Olga Russakovsky, Jia Deng, Hao Su, et al.",
      year: 2015,
      venue: "IJCV",
      era: 2,
      impact: 3,
      oneLiner: "The benchmark that drove the deep learning revolution \u2014 ImageNet gave the field a shared challenge and 1.2 million labeled images.",
      problem: "Computer vision lacked a large-scale, standardized benchmark. Datasets were small (<100K images), task-specific, and not comparable across methods.",
      insight: "Create a massive (1.2M images, 1000 classes), carefully curated image classification benchmark with annual competitions. This created a \"common task framework\" that drove rapid progress and made results directly comparable.",
      holds: "ImageNet-pretrained models are still widely used for transfer learning. The \"pretrain on large data, fine-tune on your task\" paradigm it established is THE paradigm for all of modern AI.",
      superseded: "ImageNet has known biases (geographic, demographic). Models now pretrain on web-scale data (LAION, Common Crawl). The classification-only focus misses detection, segmentation, etc.",
      practitioner: "ImageNet is the reason we have pretrained models. Every time you use a pretrained backbone, you're benefiting from what ImageNet started.",
      tags: ["dataset", "benchmark", "computer-vision", "transfer-learning"],
      deps: [5, 8],
      unlocks: [28],
      link: "https://arxiv.org/abs/1409.0575"
    },
    {
      id: 20,
      title: "Attention Is All You Need",
      shortTitle: "Transformer",
      authors: "Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan Gomez, \u0141ukasz Kaiser, Illia Polosukhin",
      year: 2017,
      venue: "NeurIPS",
      era: 3,
      impact: 3,
      oneLiner: "Replace recurrence entirely with self-attention \u2014 the Transformer architecture that powers GPT, BERT, and virtually all modern AI.",
      problem: "RNNs/LSTMs processed sequences one token at a time \u2014 inherently sequential, slow, and struggled with long-range dependencies despite attention.",
      insight: "Use ONLY attention (no recurrence). Self-attention lets every token attend to every other token in parallel. Multi-head attention captures different types of relationships. Positional encodings inject sequence order. The result: massively parallelizable, better at long-range dependencies, and scales beautifully with compute.",
      holds: "The Transformer IS modern AI. GPT-4, Claude, Gemini, Llama, Stable Diffusion, ViT, DALL-E \u2014 all Transformers. 170,000+ citations. The most important ML paper of the decade, possibly ever.",
      superseded: "Sinusoidal positional encodings were replaced by RoPE and ALiBi. The original encoder-decoder split into encoder-only (BERT) and decoder-only (GPT). Efficiency improvements (Flash Attention, linear attention) address the O(n\u00B2) cost.",
      practitioner: "If you only deeply understand ONE paper in AI, make it this one. Understand queries, keys, values. Understand multi-head attention. Understand why self-attention captures dependencies that RNNs miss. This is THE architecture.",
      tags: ["transformer", "attention", "architecture", "nlp", "foundational"],
      deps: [7, 11, 12, 17],
      unlocks: [21, 22, 25, 28, 29, 31, 32, 35, 38, 39, 40, 41, 43, 44, 45, 46, 47, 49, 50],
      link: "https://arxiv.org/abs/1706.03762"
    },
    {
      id: 21,
      title: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding",
      shortTitle: "BERT",
      authors: "Jacob Devlin, Ming-Wei Chang, Kenton Lee, Kristina Toutanova (Google)",
      year: 2018,
      venue: "NAACL 2019",
      era: 3,
      impact: 3,
      oneLiner: "Bidirectional pretraining with masked language modeling \u2014 BERT made transfer learning the default for NLP.",
      problem: "NLP models were trained from scratch for each task. Word2Vec gave static embeddings but didn't capture context (\"bank\" means different things in different sentences).",
      insight: "Pretrain a Transformer ENCODER on two tasks: (1) Masked Language Modeling \u2014 randomly mask 15% of tokens, predict them from context (bidirectional!), and (2) Next Sentence Prediction. Then fine-tune on any downstream task. Achieved SOTA on 11 NLP benchmarks simultaneously.",
      holds: "The pretrain-then-fine-tune paradigm BERT popularized is still the standard approach. Encoder models are still used for classification, NER, and semantic search. Sentence-BERT powers most embedding-based retrieval.",
      superseded: "Decoder-only models (GPT-3+) largely replaced encoders for generative tasks. NSP was shown to be unnecessary (RoBERTa). For many tasks, prompting a large LLM beats fine-tuning BERT.",
      practitioner: "If you're building search, classification, or embedding systems, you're probably using a BERT descendant. Understanding masked LM and bidirectional context is key.",
      tags: ["transformer", "nlp", "pretraining", "transfer-learning", "encoder"],
      deps: [12, 20],
      unlocks: [31, 32, 40, 43],
      link: "https://arxiv.org/abs/1810.04805"
    },
    {
      id: 22,
      title: "Improving Language Understanding by Generative Pre-Training",
      shortTitle: "GPT-1",
      authors: "Alec Radford, Karthik Narasimhan, Tim Salimans, Ilya Sutskever (OpenAI)",
      year: 2018,
      venue: "OpenAI Technical Report",
      era: 3,
      impact: 3,
      oneLiner: "Generative pretraining on unlabeled text creates powerful representations \u2014 the first GPT showed that language modeling IS the universal pre-training task.",
      problem: "Supervised NLP required expensive labeled data for each task. Unsupervised pretraining methods existed but weren't clearly better than training from scratch.",
      insight: "Pretrain a decoder-only Transformer on a large corpus using simple next-token prediction (language modeling). Then fine-tune with a supervised objective. The pretrained model already \"understands\" language \u2014 fine-tuning just points it at the right task.",
      holds: "Next-token prediction is literally how every GPT, Llama, and Claude model is trained. The insight that unsupervised language modeling creates general intelligence is the foundation of the LLM era.",
      superseded: "GPT-1 was small (117M params) and still required task-specific fine-tuning. GPT-2/3 showed that scaling eliminates the need for fine-tuning (in-context learning). The specific fine-tuning approach was replaced by prompting.",
      practitioner: "GPT-1 is the proof of concept that \"just predict the next word\" creates intelligence. Every LLM you use descends from this insight.",
      tags: ["transformer", "nlp", "pretraining", "generative", "decoder-only"],
      deps: [12, 20],
      unlocks: [23, 24, 25, 31, 39, 43],
      link: "https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf"
    },
    {
      id: 23,
      title: "Language Models are Unsupervised Multitask Learners",
      shortTitle: "GPT-2",
      authors: "Alec Radford, Jeffrey Wu, Rewon Child, David Luan, Dario Amodei, Ilya Sutskever (OpenAI)",
      year: 2019,
      venue: "OpenAI Technical Report",
      era: 3,
      impact: 3,
      oneLiner: "Scale up GPT to 1.5B parameters and it learns to do tasks it was never explicitly trained on \u2014 zero-shot transfer from pure language modeling.",
      problem: "NLP models needed fine-tuning for each new task. Transfer learning (BERT, GPT-1) required labeled examples.",
      insight: "A large enough language model trained on diverse internet text can perform tasks like translation, summarization, and Q&A WITHOUT any task-specific training. Just format the task as a text prompt. This was the first hint of \"emergent abilities\" from scale.",
      holds: "The zero-shot paradigm is exactly how people use ChatGPT, Claude, etc. The idea that scale creates capabilities is the core thesis of the LLM industry.",
      superseded: "GPT-2 was \"controversially\" not released initially (now seems quaint). GPT-3 was 100x larger and far more capable. The specific model is completely outdated.",
      practitioner: "GPT-2 introduced the idea that prompting > fine-tuning. This is the philosophical shift from \"train a model for each task\" to \"train one model that does everything.\"",
      tags: ["transformer", "nlp", "scaling", "zero-shot", "generative"],
      deps: [22],
      unlocks: [24],
      link: "https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf"
    },

    // ========== ERA 4: THE LLM AGE ==========
    {
      id: 24,
      title: "Language Models are Few-Shot Learners",
      shortTitle: "GPT-3",
      authors: "Tom Brown, Benjamin Mann, Nick Ryder, et al. (OpenAI)",
      year: 2020,
      venue: "NeurIPS",
      era: 4,
      impact: 3,
      oneLiner: "175 billion parameters and in-context learning \u2014 GPT-3 showed that scale creates genuinely new capabilities and launched the LLM era.",
      problem: "Even GPT-2's zero-shot abilities were limited. For most tasks, fine-tuning was still necessary to get good performance.",
      insight: "At 175B parameters, something qualitatively different happens: the model can learn new tasks from just a few examples IN the prompt (in-context learning / few-shot). No gradient updates needed. Format the task, give examples, and the model generalizes. This wasn't explicitly trained \u2014 it emerged from scale.",
      holds: "In-context learning is how everyone uses LLMs today. The API-based paradigm GPT-3 created (send prompts, get completions) is the entire LLM industry.",
      superseded: "GPT-3 base model was not instruction-following or safe. InstructGPT/RLHF fixed this. Chinchilla showed GPT-3 was undertrained. Open models (Llama) democratized access.",
      practitioner: "GPT-3 is year zero of the LLM era. Understanding in-context learning \u2014 how models learn from examples in the prompt without weight updates \u2014 is essential for prompt engineering.",
      tags: ["llm", "scaling", "few-shot", "in-context-learning", "emergent-abilities"],
      deps: [22, 23],
      unlocks: [25, 32, 36, 37, 38, 39, 40, 43, 49],
      link: "https://arxiv.org/abs/2005.14165"
    },
    {
      id: 25,
      title: "Scaling Laws for Neural Language Models",
      shortTitle: "Scaling Laws",
      authors: "Jared Kaplan, Sam McCandlish, Tom Henighan, et al. (OpenAI)",
      year: 2020,
      venue: "arXiv",
      era: 4,
      impact: 3,
      oneLiner: "Performance improves as a smooth power law with model size, data size, and compute \u2014 the scaling laws that gave labs the confidence to spend billions.",
      problem: "Training large models was expensive and risky. There was no principled way to predict whether a larger model would be worth the investment.",
      insight: "Language model loss follows smooth power laws as functions of model size (N), dataset size (D), and training compute (C). These relationships are remarkably predictable across many orders of magnitude. Conclusion: bigger models, more data, more compute = better performance, reliably.",
      holds: "Scaling laws remain the strategic foundation for frontier AI labs. They're why OpenAI, Anthropic, Google, etc. keep building bigger models and bigger clusters.",
      superseded: "The original Kaplan scaling laws overweighted model size vs. data size. Chinchilla (2022) showed that data scaling was underappreciated \u2014 you need to scale data proportionally.",
      practitioner: "Scaling laws explain WHY the AI industry looks the way it does \u2014 massive compute investments, billion-parameter models, trillion-token datasets. Understanding them helps you predict what's coming next.",
      tags: ["llm", "scaling", "theory", "compute", "power-laws"],
      deps: [20, 22, 24],
      unlocks: [36, 39, 43, 44],
      link: "https://arxiv.org/abs/2001.08361"
    },
    {
      id: 26,
      title: "You Only Look Once: Unified, Real-Time Object Detection",
      shortTitle: "YOLO",
      authors: "Joseph Redmon, Santosh Divvala, Ross Girshick, Ali Farhadi",
      year: 2016,
      venue: "CVPR",
      era: 2,
      impact: 2,
      oneLiner: "Frame object detection as a single regression problem \u2014 one forward pass gives you bounding boxes and class probabilities. Real-time detection was born.",
      problem: "Object detection used multi-stage pipelines (R-CNN: propose regions \u2192 classify each). Accurate but painfully slow \u2014 47 seconds per image for R-CNN.",
      insight: "Divide the image into a grid. Each grid cell predicts bounding boxes and class probabilities simultaneously in a single pass. No region proposals, no post-processing pipeline. 45 FPS on a GPU. Detection in real-time.",
      holds: "YOLO is still the go-to for real-time detection. YOLOv8/v9 are production staples. The single-shot detection paradigm it created dominates edge deployment.",
      superseded: "The original YOLO had poor accuracy on small objects and nearby objects. Modern versions (v5-v9) fixed these with multi-scale detection, better backbones, etc.",
      practitioner: "If you need real-time object detection (autonomous driving, robotics, surveillance, manufacturing QA), you're probably using a YOLO variant. It's the most deployed detection model in the world.",
      tags: ["computer-vision", "object-detection", "real-time", "production"],
      deps: [5, 8, 17],
      unlocks: [],
      link: "https://arxiv.org/abs/1506.02640"
    },
    {
      id: 27,
      title: "U-Net: Convolutional Networks for Biomedical Image Segmentation",
      shortTitle: "U-Net",
      authors: "Olaf Ronneberger, Philipp Fischer, Thomas Brox",
      year: 2015,
      venue: "MICCAI",
      era: 2,
      impact: 2,
      oneLiner: "An encoder-decoder with skip connections that segments images pixel-by-pixel \u2014 the architecture that powers medical imaging AND Stable Diffusion.",
      problem: "Image segmentation needed large amounts of labeled data. Biomedical imaging had tiny datasets (sometimes <50 images). Existing architectures couldn't produce precise pixel-level masks.",
      insight: "Encode-then-decode architecture with skip connections that concatenate features from the encoder directly to the decoder at matching resolutions. This preserves fine-grained spatial information while leveraging high-level features. Works with heavy data augmentation on tiny datasets.",
      holds: "U-Net is the backbone of diffusion models \u2014 Stable Diffusion, DALL-E 2, Imagen all use U-Net variants as their denoising network. Also still standard in medical imaging.",
      superseded: "Modern variants (nnU-Net, Swin-UNet) use better building blocks. Diffusion Transformers (DiT) are replacing U-Net in the latest generation of diffusion models.",
      practitioner: "U-Net connects two worlds: medical imaging and generative AI. If you work with Stable Diffusion or any diffusion model, you're using a U-Net descendant.",
      tags: ["computer-vision", "segmentation", "medical-imaging", "encoder-decoder", "diffusion"],
      deps: [5, 17],
      unlocks: [33, 34],
      link: "https://arxiv.org/abs/1505.04597"
    },
    {
      id: 28,
      title: "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale",
      shortTitle: "ViT",
      authors: "Alexey Dosovitskiy, Lucas Beyer, Alexander Kolesnikov, et al. (Google)",
      year: 2021,
      venue: "ICLR",
      era: 4,
      impact: 3,
      oneLiner: "Cut images into patches, treat them as tokens, and feed them to a standard Transformer \u2014 proving that convolutions aren't necessary for vision.",
      problem: "Computer vision was \"CNN territory.\" Transformers worked for language but couldn't match CNNs on vision benchmarks. The inductive biases of convolutions seemed essential.",
      insight: "Split an image into 16\u00D716 patches, linearly embed each patch, add position embeddings, and feed the sequence to a standard Transformer encoder. With enough pretraining data, ViT matches or beats the best CNNs. The Transformer architecture is universal.",
      holds: "ViT and its descendants (DINOv2, SigLIP) are the standard for vision encoders. CLIP uses ViT. Most modern vision-language models use ViT. The patch-as-token paradigm is now standard.",
      superseded: "Original ViT needs massive pretraining data. DeiT showed data-efficient ViT training. Hybrid approaches (ConvNeXt) showed you can make CNNs competitive with modern training recipes.",
      practitioner: "ViT is critical because it unified the architecture for vision AND language. This is why multimodal models (CLIP, GPT-4V, LLaVA) work \u2014 same architecture processes both modalities.",
      tags: ["transformer", "computer-vision", "architecture", "patches", "foundation-model"],
      deps: [17, 19, 20],
      unlocks: [29, 35, 46, 47, 48, 50],
      link: "https://arxiv.org/abs/2010.11929"
    },
    {
      id: 29,
      title: "Learning Transferable Visual Models From Natural Language Supervision",
      shortTitle: "CLIP",
      authors: "Alec Radford, Jong Wook Kim, Chris Hallacy, et al. (OpenAI)",
      year: 2021,
      venue: "ICML",
      era: 4,
      impact: 3,
      oneLiner: "Train on 400M image-text pairs with contrastive learning \u2014 CLIP connected vision and language and enabled zero-shot image classification.",
      problem: "Vision models could only recognize classes they were trained on. Adding a new category required new labeled data and retraining. Vision and language were separate worlds.",
      insight: "Jointly train an image encoder (ViT) and text encoder (Transformer) to map matching image-text pairs close together in embedding space using contrastive loss. At inference, classify any image by checking which text description is closest. Zero-shot classification with natural language.",
      holds: "CLIP is EVERYWHERE. It's the vision encoder for DALL-E, Stable Diffusion, and most vision-language models. CLIP embeddings power image search, content moderation, and recommendation systems.",
      superseded: "SigLIP improved the loss function (sigmoid > softmax). OpenCLIP scaled it further. Newer models (EVA-CLIP, DFN-CLIP) improve data quality. But the CLIP paradigm itself is dominant.",
      practitioner: "CLIP is one of the most practically useful models ever created. If you need to connect images to text, you're using CLIP or a descendant. Understanding contrastive learning through CLIP is essential.",
      tags: ["multimodal", "vision-language", "contrastive-learning", "zero-shot", "embeddings"],
      deps: [17, 20, 28],
      unlocks: [34, 35, 43, 46, 47, 48, 50],
      link: "https://arxiv.org/abs/2103.00020"
    },
    {
      id: 30,
      title: "A Style-Based Generator Architecture for Generative Adversarial Networks",
      shortTitle: "StyleGAN",
      authors: "Tero Karras, Samuli Laine, Timo Aila (NVIDIA)",
      year: 2019,
      venue: "CVPR",
      era: 3,
      impact: 2,
      oneLiner: "Control image generation at different scales \u2014 StyleGAN separated coarse structure from fine details and produced the most realistic face images ever.",
      problem: "GANs could generate images but offered limited control over the output. Understanding and manipulating what the generator learned was difficult.",
      insight: "Use a mapping network to transform random noise into a \"style\" vector, then inject this style at different layers of the generator. Early layers control coarse features (pose, face shape), later layers control fine details (hair, freckles). Adaptive instance normalization (AdaIN) applies the style.",
      holds: "StyleGAN3 and style-based architectures are still used for face generation, art, and creative tools. The concept of disentangled style control influenced diffusion model conditioning.",
      superseded: "For general image generation, diffusion models produce better results with more diversity. StyleGAN's training is still unstable on diverse datasets beyond faces.",
      practitioner: "StyleGAN demonstrated that you can have fine-grained control over generation. This \"control at different scales\" idea shows up in diffusion model guidance (ControlNet, IP-Adapter).",
      tags: ["generative", "gan", "style-transfer", "face-generation", "control"],
      deps: [13],
      unlocks: [],
      link: "https://arxiv.org/abs/1812.04948"
    },
    {
      id: 31,
      title: "Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer",
      shortTitle: "T5",
      authors: "Colin Raffel, Noam Shazeer, Adam Roberts, et al. (Google)",
      year: 2020,
      venue: "JMLR",
      era: 4,
      impact: 2,
      oneLiner: "Frame EVERY NLP task as text-to-text \u2014 T5 unified the field and showed that one format rules them all.",
      problem: "Different NLP tasks used different architectures and training objectives. Classification used encoders, generation used decoders, seq2seq used both. No unified framework.",
      insight: "Convert every NLP task to text-in, text-out format. Classification? \"classify: The movie was great\" \u2192 \"positive.\" Summarization? \"summarize: [long text]\" \u2192 \"[summary].\" Same model, same loss, same API for everything.",
      holds: "The text-to-text format is literally how every LLM API works today. The systematic comparison of pretraining objectives in T5's paper is one of the best empirical studies in ML.",
      superseded: "T5's encoder-decoder architecture lost to decoder-only (GPT) for most generative tasks. The specific model is outdated. But the unification principle won completely.",
      practitioner: "T5 is why you can ask ChatGPT to do classification, summarization, translation, and code generation with the same API. The text-to-text paradigm simplified everything.",
      tags: ["transformer", "nlp", "unified-framework", "transfer-learning", "encoder-decoder"],
      deps: [20, 21, 22],
      unlocks: [35, 40],
      link: "https://arxiv.org/abs/1910.10683"
    },
    {
      id: 32,
      title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
      shortTitle: "RAG",
      authors: "Patrick Lewis, Ethan Perez, Aleksandra Piktus, et al. (Meta)",
      year: 2020,
      venue: "NeurIPS",
      era: 4,
      impact: 3,
      oneLiner: "Give the model a search engine \u2014 RAG combines retrieval and generation so LLMs can use external knowledge instead of hallucinating.",
      problem: "Language models could only use knowledge stored in their parameters. They'd confidently hallucinate facts, couldn't access up-to-date information, and had no way to cite sources.",
      insight: "At inference time, retrieve relevant documents from an external knowledge base (using dense retrieval), then condition the language model's generation on both the query AND the retrieved documents. The retriever and generator can be trained end-to-end.",
      holds: "RAG is THE production pattern for enterprise AI. Every chatbot that answers questions about company documents uses RAG. It's the most practically important LLM architecture pattern.",
      superseded: "The original DPR retriever has been replaced by better retrievers (ColBERT, BGE, GTE). Modern RAG uses chunking strategies, re-ranking, and hybrid search. But the core pattern is unchanged.",
      practitioner: "If you're building ANY LLM application that needs factual accuracy, you need RAG. Understanding retrieval, embedding, chunking, and generation pipelines is the #1 production LLM skill.",
      tags: ["llm", "retrieval", "knowledge", "production", "rag"],
      deps: [20, 21, 24],
      unlocks: [43],
      link: "https://arxiv.org/abs/2005.11401"
    },
    {
      id: 33,
      title: "Denoising Diffusion Probabilistic Models",
      shortTitle: "DDPM",
      authors: "Jonathan Ho, Ajay Jain, Pieter Abbeel",
      year: 2020,
      venue: "NeurIPS",
      era: 4,
      impact: 3,
      oneLiner: "Slowly add noise to images, then learn to reverse the process \u2014 diffusion models overtook GANs and launched the generative AI image revolution.",
      problem: "GANs produced sharp images but were unstable to train, suffered from mode collapse, and lacked diversity. VAEs were stable but produced blurry outputs.",
      insight: "Forward process: gradually add Gaussian noise to an image over T steps until it becomes pure noise. Reverse process: train a neural network (U-Net) to predict and remove the noise at each step. Start from random noise, iteratively denoise, and you get a new image. Simple, stable, and produces diverse outputs.",
      holds: "Diffusion is the dominant paradigm for image, video, and audio generation. Stable Diffusion, DALL-E 3, Midjourney, Sora \u2014 all diffusion models.",
      superseded: "The original DDPM was slow (1000 denoising steps). DDIM, DPM-Solver, and consistency models dramatically reduced steps. Latent diffusion moved the process to a compressed latent space.",
      practitioner: "If you're working in generative AI, understanding diffusion is non-negotiable. The forward/reverse process, noise scheduling, and U-Net denoising architecture are fundamental.",
      tags: ["generative", "diffusion", "image-generation", "denoising"],
      deps: [14, 17, 27],
      unlocks: [34, 35],
      link: "https://arxiv.org/abs/2006.11239"
    },
    {
      id: 34,
      title: "High-Resolution Image Synthesis with Latent Diffusion Models",
      shortTitle: "Stable Diffusion",
      authors: "Robin Rombach, Andreas Blattmann, Dominik Lorenz, Patrick Esser, Bj\u00F6rn Ommer",
      year: 2022,
      venue: "CVPR",
      era: 4,
      impact: 3,
      oneLiner: "Run diffusion in a compressed latent space instead of pixel space \u2014 Latent Diffusion made high-res generation practical and Stable Diffusion accessible to everyone.",
      problem: "Diffusion models worked on pixel space which was computationally brutal for high-resolution images (512\u00D7512+ was impractical).",
      insight: "First train a VAE to encode images into a compact latent space (e.g., 64\u00D764\u00D74 instead of 512\u00D7512\u00D73). Then run the diffusion process in this latent space \u2014 same quality, fraction of the compute. Cross-attention layers condition on text (via CLIP text encoder).",
      holds: "Latent diffusion IS the architecture behind Stable Diffusion, DALL-E 3, and most production image generators. The VAE + diffusion + text conditioning pipeline is the standard.",
      superseded: "U-Net is being replaced by DiT (Diffusion Transformer) in newer models. SDXL and SD3 improved the architecture significantly. But LDM's core insight remains.",
      practitioner: "This is the paper behind Stable Diffusion \u2014 the most widely used open-source generative model. Understanding the VAE encoder \u2192 latent diffusion \u2192 VAE decoder pipeline is essential.",
      tags: ["generative", "diffusion", "latent-space", "image-generation", "production"],
      deps: [14, 27, 29, 33],
      unlocks: [],
      link: "https://arxiv.org/abs/2112.10752"
    },
    {
      id: 35,
      title: "Photorealistic Text-to-Image Diffusion Models with Deep Language Understanding",
      shortTitle: "Imagen",
      authors: "Chitwan Saharia, William Chan, Saurabh Saxena, et al. (Google)",
      year: 2022,
      venue: "NeurIPS",
      era: 4,
      impact: 2,
      oneLiner: "Use a large frozen language model (T5-XXL) as the text encoder for diffusion \u2014 Imagen showed that better text understanding = better images.",
      problem: "Text-to-image models used CLIP text encoders which had limited language understanding. Complex prompts with attributes, spatial relationships, and counting were poorly handled.",
      insight: "Replace CLIP's text encoder with a large pretrained language model (T5-XXL, 4.6B params). Don't fine-tune the language model \u2014 just use its rich text representations to condition the diffusion model. Better language understanding directly translates to better image generation.",
      holds: "The insight that text encoder quality is the bottleneck drove DALL-E 3 (GPT-4 for caption rewriting) and SD3 (T5). Text understanding matters more than diffusion architecture.",
      superseded: "Imagen wasn't open-sourced. Stable Diffusion (open, latent space) became the standard. The cascaded diffusion approach was superseded by latent diffusion.",
      practitioner: "Imagen's key lesson: the text encoder is the bottleneck, not the diffusion model. If your generated images don't match the prompt, improve the text conditioning.",
      tags: ["generative", "diffusion", "text-to-image", "language-conditioning"],
      deps: [20, 28, 29, 31, 33],
      unlocks: [],
      link: "https://arxiv.org/abs/2205.11487"
    },
    {
      id: 36,
      title: "Training Compute-Optimal Large Language Models",
      shortTitle: "Chinchilla",
      authors: "Jordan Hoffmann, Sebastian Borgeaud, Arthur Mensch, et al. (DeepMind)",
      year: 2022,
      venue: "NeurIPS",
      era: 4,
      impact: 3,
      oneLiner: "The LLM industry was training models that were too big and not feeding them enough data \u2014 Chinchilla showed compute-optimal scaling requires proportional data.",
      problem: "Labs followed Kaplan scaling laws which suggested prioritizing model size over data. GPT-3 (175B params) was trained on \"only\" 300B tokens.",
      insight: "For a given compute budget, model size and training data should be scaled EQUALLY. A 70B parameter model trained on 1.4T tokens (Chinchilla) outperforms a 280B model trained on 300B tokens (Gopher) using the same compute. The industry was massively over-parameterized and under-trained.",
      holds: "Chinchilla scaling laws redirected the entire industry toward better data. Llama, Mistral, and most modern models follow Chinchilla-optimal ratios. Data quality became the priority.",
      superseded: "\"Over-training\" smaller models beyond Chinchilla-optimal (like Llama 3) is actually preferred for inference efficiency. The original scaling laws don't account for inference costs.",
      practitioner: "Chinchilla is why Llama-70B beats GPT-3-175B \u2014 it was trained on way more data. For your own projects: if your model underperforms, train longer on more data before making it bigger.",
      tags: ["llm", "scaling", "compute-optimal", "data", "efficiency"],
      deps: [24, 25],
      unlocks: [39, 42, 43, 44],
      link: "https://arxiv.org/abs/2203.15556"
    },
    {
      id: 37,
      title: "Training Language Models to Follow Instructions with Human Feedback",
      shortTitle: "InstructGPT / RLHF",
      authors: "Long Ouyang, Jeff Wu, Xu Jiang, et al. (OpenAI)",
      year: 2022,
      venue: "NeurIPS",
      era: 4,
      impact: 3,
      oneLiner: "Fine-tune GPT-3 with human feedback to make it actually helpful, harmless, and honest \u2014 the alignment technique that made ChatGPT possible.",
      problem: "GPT-3 was powerful but often unhelpful \u2014 it would ignore instructions, generate toxic content, or just autocomplete text rather than answer questions. Raw language models aren't aligned with what users actually want.",
      insight: "Three steps: (1) Supervised fine-tuning on high-quality human demonstrations. (2) Train a reward model on human preference comparisons (which response is better?). (3) Use PPO (reinforcement learning) to fine-tune the model to maximize the reward model's score. The 1.3B InstructGPT was preferred over the 175B GPT-3.",
      holds: "RLHF (or its variants like DPO, RLAIF) is how EVERY production LLM is aligned \u2014 ChatGPT, Claude, Gemini, Llama. The insight that human preferences > raw capability is fundamental to safe AI deployment.",
      superseded: "PPO is complex and unstable. DPO simplified the process. Constitutional AI uses AI feedback instead of human labelers. But the core paradigm remains.",
      practitioner: "RLHF is why ChatGPT feels helpful while raw GPT-3 felt like autocomplete. Understanding alignment \u2014 reward modeling, preference learning, the RLHF pipeline \u2014 is essential for anyone deploying LLMs.",
      tags: ["llm", "alignment", "rlhf", "safety", "human-feedback"],
      deps: [15, 16, 24],
      unlocks: [43, 45],
      link: "https://arxiv.org/abs/2203.02155"
    },
    {
      id: 38,
      title: "Chain-of-Thought Prompting Elicits Reasoning in Large Language Models",
      shortTitle: "Chain-of-Thought",
      authors: "Jason Wei, Xuezhi Wang, Dale Schuurmans, et al. (Google)",
      year: 2022,
      venue: "NeurIPS",
      era: 4,
      impact: 3,
      oneLiner: "Show the model how to think step-by-step and it can actually reason \u2014 Chain-of-Thought unlocked mathematical and logical reasoning in LLMs.",
      problem: "LLMs failed at multi-step reasoning \u2014 math problems, logical deductions, multi-hop questions. They'd jump to answers without working through the steps.",
      insight: "Include step-by-step reasoning examples in the prompt (few-shot CoT) or simply add \"Let's think step by step\" (zero-shot CoT). The model then generates intermediate reasoning steps before the final answer. This dramatically improves performance on math, logic, and commonsense reasoning.",
      holds: "CoT is the foundation of reasoning in LLMs. OpenAI's o1/o3, Claude's extended thinking \u2014 these are all descendants of CoT. The \"think before you answer\" paradigm is now standard.",
      superseded: "Simple CoT evolved into Tree of Thoughts, self-consistency, and eventually trained reasoning (o1-style models that internalize CoT during training rather than relying on prompting).",
      practitioner: "If your LLM struggles with complex tasks, add \"think step by step\" or provide reasoning examples. CoT is the single most important prompting technique.",
      tags: ["llm", "reasoning", "prompting", "chain-of-thought"],
      deps: [20, 24],
      unlocks: [49],
      link: "https://arxiv.org/abs/2201.11903"
    },

    // ========== ERA 5: THE FRONTIER ==========
    {
      id: 39,
      title: "LLaMA: Open and Efficient Foundation Language Models",
      shortTitle: "LLaMA",
      authors: "Hugo Touvron, Thibaut Lavril, Gautier Izacard, et al. (Meta)",
      year: 2023,
      venue: "arXiv",
      era: 5,
      impact: 3,
      oneLiner: "A 65B parameter open model that matches GPT-3 quality \u2014 LLaMA democratized LLM research and spawned an entire open-source ecosystem.",
      problem: "The best LLMs (GPT-3, PaLM) were closed-source and API-only. Researchers couldn't study, modify, or build on them. Innovation was centralized.",
      insight: "Train relatively small models (7B-65B) on MUCH more data (1-1.4T tokens) \u2014 following Chinchilla scaling laws. LLaMA-13B outperforms GPT-3 (175B) on most benchmarks. Smaller, better-trained models beat bigger, undertrained ones.",
      holds: "LLaMA spawned Alpaca, Vicuna, and the entire open-source LLM ecosystem. Llama 2 and 3 are the backbone of most open-source AI. The \"small but well-trained\" paradigm is now standard.",
      superseded: "LLaMA 1 had a restrictive license. Llama 2 and 3 are properly open. Mistral, Qwen, and others now compete. But LLaMA started the open-source LLM movement.",
      practitioner: "LLaMA is why you can run an LLM on your laptop. Understanding the open-source LLM ecosystem \u2014 fine-tuning, quantization, deployment of LLaMA-family models \u2014 is a critical production skill.",
      tags: ["llm", "open-source", "efficient", "foundation-model"],
      deps: [20, 22, 24, 25, 36],
      unlocks: [42, 43, 44, 46],
      link: "https://arxiv.org/abs/2302.13971"
    },
    {
      id: 40,
      title: "LoRA: Low-Rank Adaptation of Large Language Models",
      shortTitle: "LoRA",
      authors: "Edward Hu, Yelong Shen, Phillip Wallis, et al. (Microsoft)",
      year: 2022,
      venue: "ICLR",
      era: 5,
      impact: 3,
      oneLiner: "Fine-tune billion-parameter models by training only tiny low-rank matrices \u2014 LoRA made LLM adaptation practical for everyone.",
      problem: "Fine-tuning a 175B parameter model required enormous GPU memory (storing full optimizer states for every parameter). Fine-tuning was only feasible for large labs.",
      insight: "Freeze the pretrained weights entirely. For each weight matrix W, train only two small matrices A and B where \u0394W = BA (low-rank decomposition). With rank 4-16, you're training <1% of the parameters but getting similar performance to full fine-tuning. Adapters can be swapped at inference time.",
      holds: "LoRA and QLoRA are THE standard for LLM fine-tuning. Every production deployment that needs customization uses LoRA. It's in Hugging Face PEFT, axolotl, and every fine-tuning framework.",
      superseded: "DoRA and LoRA+ improve on the original. QLoRA combines quantization + LoRA for even less memory. Full fine-tuning still wins when you have the resources and data.",
      practitioner: "If you need to customize an LLM for your domain, LoRA is your first tool. I used LoRA for my Text-to-SQL fine-tuning project. Understanding rank selection, which layers to adapt, and when to use it vs. prompting is a key production skill.",
      tags: ["llm", "fine-tuning", "efficiency", "adaptation", "parameter-efficient"],
      deps: [20, 21, 24, 31],
      unlocks: [42, 43],
      link: "https://arxiv.org/abs/2106.09685"
    },
    {
      id: 41,
      title: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
      shortTitle: "FlashAttention",
      authors: "Tri Dao, Daniel Fu, Stefano Ermon, Atri Rudra, Christopher R\u00E9",
      year: 2022,
      venue: "NeurIPS",
      era: 5,
      impact: 2,
      oneLiner: "Make attention fast by respecting GPU memory hierarchy \u2014 FlashAttention is 2-4x faster with no approximation.",
      problem: "Standard attention scales O(n\u00B2) in both compute and memory. For long sequences (4K+ tokens), the N\u00D7N attention matrix dominated memory and runtime.",
      insight: "Standard implementations wastefully move data between GPU HBM (slow, large) and SRAM (fast, small). FlashAttention tiles the attention computation, keeping data in fast SRAM, using online softmax to avoid materializing the full N\u00D7N matrix. EXACT attention, no approximation, but 2-4x faster and much less memory.",
      holds: "FlashAttention (now v3) is used in EVERY serious LLM implementation. It's in PyTorch natively. It enables the long context windows (128K+ tokens) in modern LLMs.",
      superseded: "FlashAttention 2 and 3 improved on the original. Ring attention enables even longer contexts across GPUs. But the IO-aware computing principle is permanent.",
      practitioner: "You don't need to implement FlashAttention, but understanding why it works (GPU memory hierarchy, tiling, IO-awareness) helps you write efficient training code.",
      tags: ["efficiency", "attention", "gpu", "systems", "infrastructure"],
      deps: [20],
      unlocks: [43, 44],
      link: "https://arxiv.org/abs/2205.14135"
    },
    {
      id: 42,
      title: "QLoRA: Efficient Finetuning of Quantized LLMs",
      shortTitle: "QLoRA",
      authors: "Tim Dettmers, Artidoro Pagnoni, Ari Holtzman, Luke Zettlemoyer",
      year: 2023,
      venue: "NeurIPS",
      era: 5,
      impact: 2,
      oneLiner: "Fine-tune a 65B parameter model on a single 48GB GPU \u2014 QLoRA combines 4-bit quantization with LoRA for extreme efficiency.",
      problem: "Even with LoRA, fine-tuning large models (33B+) required multiple expensive GPUs because the base model weights still needed to be loaded in full precision.",
      insight: "Quantize the base model to 4-bit precision (NormalFloat4, a new data type optimized for neural network weights), then apply LoRA adapters in full precision on top. Double quantization reduces memory further. Paged optimizers handle memory spikes. Fine-tune a 65B model on a single 48GB GPU.",
      holds: "QLoRA is the standard for fine-tuning large models on consumer hardware. It democratized LLM customization \u2014 you can fine-tune Llama on a single A100 or even an RTX 4090.",
      superseded: "GPTQ and AWQ offer alternative quantization. GGUF format (for llama.cpp) is preferred for inference. But QLoRA for training remains dominant.",
      practitioner: "QLoRA is how you fine-tune models in practice. If you can't afford 8xA100s, QLoRA lets you customize a 70B model on hardware you can actually afford.",
      tags: ["llm", "fine-tuning", "quantization", "efficiency", "accessible"],
      deps: [36, 39, 40],
      unlocks: [],
      link: "https://arxiv.org/abs/2305.14314"
    },
    {
      id: 43,
      title: "GPT-4 Technical Report",
      shortTitle: "GPT-4",
      authors: "OpenAI",
      year: 2023,
      venue: "arXiv / OpenAI",
      era: 5,
      impact: 3,
      oneLiner: "The model that made AI mainstream \u2014 GPT-4 is multimodal, passes bar exams, and set the standard for what LLMs can do.",
      problem: "GPT-3/3.5 were impressive but still made obvious errors, couldn't handle images, and struggled with complex reasoning tasks.",
      insight: "While the technical details are largely undisclosed, GPT-4 demonstrated that scaling (likely ~1T+ params, MoE architecture), careful RLHF, and multimodal training produce dramatically more capable and reliable models. It passes the bar exam (top 10%) and scores 5/5 on AP exams.",
      holds: "GPT-4 set the quality bar for what LLMs should be able to do. Its multimodal capabilities established vision-language as the default.",
      superseded: "GPT-4 Turbo, GPT-4o, Claude 3.5 Sonnet, and Gemini 1.5 all exceed GPT-4's original capabilities. Competition has driven rapid improvement.",
      practitioner: "GPT-4 is the benchmark everything is measured against. Understanding its capabilities and limitations (still hallucinates, doesn't truly \"know\" things) is essential for setting realistic expectations.",
      tags: ["llm", "multimodal", "frontier", "production", "reasoning"],
      deps: [20, 21, 22, 24, 25, 29, 32, 36, 37, 39, 40, 41],
      unlocks: [48, 49, 50],
      link: "https://arxiv.org/abs/2303.08774"
    },
    {
      id: 44,
      title: "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity",
      shortTitle: "MoE / Switch",
      authors: "William Fedus, Barret Zoph, Noam Shazeer (Google)",
      year: 2022,
      venue: "JMLR",
      era: 5,
      impact: 2,
      oneLiner: "Not every token needs every parameter \u2014 route each token to specialized \"expert\" sub-networks for massive scale at manageable compute cost.",
      problem: "Making models bigger meant proportionally more compute for every single input. A 1T parameter dense model would be computationally impossible to run.",
      insight: "Replace each feed-forward layer with multiple \"expert\" networks plus a lightweight router. For each token, the router selects 1-2 experts (out of dozens). Total parameters are huge but active parameters per token are small. Scale model capacity without scaling compute linearly.",
      holds: "MoE is how frontier models scale. GPT-4 is widely believed to be MoE. Mixtral, DeepSeek, and Grok use MoE. It's the dominant approach for frontier models.",
      superseded: "The original Switch Transformer's top-1 routing was unstable. Modern MoE uses top-2 routing, expert parallelism, and load balancing. DeepSeek-V2 introduced multi-head latent attention with MoE.",
      practitioner: "Understanding MoE is key to understanding why models like GPT-4 can be so large yet still fast. MoE models need more memory (all experts loaded) but less compute per token.",
      tags: ["llm", "architecture", "efficiency", "scaling", "mixture-of-experts"],
      deps: [20, 25, 36, 39, 41],
      unlocks: [],
      link: "https://arxiv.org/abs/2101.03961"
    },
    {
      id: 45,
      title: "Direct Preference Optimization: Your Language Model is Secretly a Reward Model",
      shortTitle: "DPO",
      authors: "Rafael Rafailov, Archit Sharma, Eric Mitchell, et al. (Stanford)",
      year: 2023,
      venue: "NeurIPS",
      era: 5,
      impact: 2,
      oneLiner: "Skip the reward model entirely \u2014 DPO directly optimizes language model preferences, making alignment simpler and more stable than RLHF.",
      problem: "RLHF required training a separate reward model, then using PPO to optimize against it. This pipeline was complex, unstable, and required significant compute.",
      insight: "Mathematically, the optimal RL policy can be expressed as a closed-form function of the reward model. This means you can directly optimize the language model on preference data (chosen vs. rejected responses) without ever training a reward model or running RL. Same result, much simpler.",
      holds: "DPO and its variants (IPO, KTO, ORPO) are widely used for alignment. It's simpler to implement and more accessible than full RLHF pipelines.",
      superseded: "Some evidence suggests PPO-based RLHF still produces better results at the frontier. Online DPO and iterative DPO address some limitations. The debate is ongoing.",
      practitioner: "If you're fine-tuning an LLM with preference data, DPO is the practical choice. It's in TRL, axolotl, and every fine-tuning toolkit.",
      tags: ["llm", "alignment", "preference-optimization", "efficiency"],
      deps: [20, 37],
      unlocks: [],
      link: "https://arxiv.org/abs/2305.18290"
    },
    {
      id: 46,
      title: "Visual Instruction Tuning",
      shortTitle: "LLaVA",
      authors: "Haotian Liu, Chunyuan Li, Qingyang Wu, Yong Jae Lee",
      year: 2023,
      venue: "NeurIPS",
      era: 5,
      impact: 2,
      oneLiner: "Connect a vision encoder to an LLM with a simple projection layer \u2014 LLaVA showed that visual instruction tuning creates powerful multimodal models cheaply.",
      problem: "Multimodal models were complex, expensive, and proprietary. Building a model that could understand images AND follow instructions required massive resources.",
      insight: "Take a pretrained CLIP vision encoder and a pretrained LLaMA language model. Connect them with a simple linear projection layer. Generate visual instruction-following data using GPT-4. Fine-tune. Result: a multimodal model built for ~$100 in compute.",
      holds: "LLaVA's architecture (vision encoder + projection + LLM) is the standard template for open-source multimodal models. LLaVA-1.5, LLaVA-NeXT, and many production models follow this pattern.",
      superseded: "More sophisticated architectures (Qwen-VL, InternVL) use better fusion methods. Training on more diverse visual data improves capability. But the simplicity of LLaVA's approach remains its strength.",
      practitioner: "LLaVA is directly relevant to my retinal disease classification work using FLAIR (a vision-language model). Understanding how vision encoders connect to LLMs is essential for multimodal AI work.",
      tags: ["multimodal", "vision-language", "instruction-tuning", "open-source"],
      deps: [20, 28, 29, 39],
      unlocks: [48, 50],
      link: "https://arxiv.org/abs/2304.08485"
    },
    {
      id: 47,
      title: "Segment Anything",
      shortTitle: "SAM",
      authors: "Alexander Kirillov, Eric Mintun, Nikhila Ravi, et al. (Meta)",
      year: 2023,
      venue: "ICCV",
      era: 5,
      impact: 2,
      oneLiner: "A foundation model for image segmentation \u2014 SAM segments anything in any image with zero-shot transfer, just like CLIP did for classification.",
      problem: "Segmentation models were task-specific \u2014 trained for specific object categories. Adding new categories required new labeled data and retraining.",
      insight: "Build a promptable segmentation model (point, box, or text prompt \u2192 segmentation mask) trained on 1 billion masks from 11 million images (SA-1B dataset). The data engine uses the model itself to assist annotation, creating a virtuous cycle.",
      holds: "SAM and SAM2 are the standard for interactive segmentation. The \"foundation model\" approach to segmentation is the established paradigm.",
      superseded: "SAM2 handles video. Faster variants (FastSAM, EfficientSAM, MobileSAM) address deployment. But the core approach is established.",
      practitioner: "SAM is incredibly useful in production \u2014 automated labeling, interactive annotation, object selection. The data engine concept (model helps create its own training data) is a powerful pattern.",
      tags: ["computer-vision", "segmentation", "foundation-model", "zero-shot", "annotation"],
      deps: [20, 28, 29],
      unlocks: [],
      link: "https://arxiv.org/abs/2304.02643"
    },
    {
      id: 48,
      title: "GPT-4V(ision) System Card",
      shortTitle: "GPT-4V",
      authors: "OpenAI",
      year: 2023,
      venue: "OpenAI Technical Report",
      era: 5,
      impact: 2,
      oneLiner: "LLMs that truly see \u2014 GPT-4V proved that large language models can natively understand images alongside text.",
      problem: "Multimodal models either used CLIP-style contrastive learning (good at matching, not reasoning) or simple projection layers (limited understanding). No model combined deep visual understanding with powerful language reasoning.",
      insight: "Integrate visual understanding directly into the LLM architecture at training time (rather than bolting it on after). GPT-4V can read charts, solve visual math problems, understand memes, describe medical images, and reason about spatial relationships.",
      holds: "Native multimodal LLMs are the standard. Claude, Gemini, GPT-4o all process images natively. The expectation that AI models handle both text and images is now universal.",
      superseded: "GPT-4o improved on GPT-4V with better efficiency and audio capabilities. Open models (LLaVA, Qwen-VL) provide competitive alternatives. Video understanding is the next frontier.",
      practitioner: "Multimodal models change what's possible \u2014 document understanding, medical imaging, visual QA, accessibility. My retinal disease classification work with FLAIR is part of this vision-language revolution.",
      tags: ["multimodal", "vision-language", "frontier", "reasoning"],
      deps: [28, 29, 43, 46],
      unlocks: [50],
      link: "https://cdn.openai.com/papers/GPTV_System_Card.pdf"
    },
    {
      id: 49,
      title: "Learning to Reason with LLMs",
      shortTitle: "o1 / Reasoning",
      authors: "OpenAI",
      year: 2024,
      venue: "OpenAI Blog / Technical Report",
      era: 5,
      impact: 2,
      oneLiner: "Give the model time to think \u2014 o1 uses internal chain-of-thought reasoning at inference time to solve problems that stumped previous LLMs.",
      problem: "LLMs could do CoT prompting but their reasoning was shallow. They failed on competition math, complex coding, and scientific reasoning.",
      insight: "Train the model to use chain-of-thought reasoning internally (not just when prompted). At inference time, the model \"thinks\" for longer on harder problems \u2014 generating internal reasoning tokens before answering. More thinking time = better answers. This is \"test-time compute scaling.\"",
      holds: "Reasoning models (o1, o3, Claude with extended thinking, DeepSeek-R1) represent the current frontier. The idea that inference-time compute can substitute for training-time compute is the newest scaling paradigm.",
      superseded: "o3 and subsequent models improve on o1. Open models (DeepSeek-R1) replicate the approach. The specific implementation details are largely undisclosed.",
      practitioner: "Reasoning models change the cost equation \u2014 they use more tokens (more expensive) but solve harder problems. Understanding when to use a reasoning model vs. a fast model is a key architecture decision.",
      tags: ["llm", "reasoning", "frontier", "test-time-compute", "chain-of-thought"],
      deps: [20, 24, 38, 43],
      unlocks: [],
      link: "https://openai.com/index/learning-to-reason-with-llms/"
    },
    {
      id: 50,
      title: "FLAIR: A Foundation LAnguage Image model of the Retina",
      shortTitle: "FLAIR",
      authors: "Julio Silva-Rodriguez, Hadi Chakor, Riadh Kobbi, et al.",
      year: 2024,
      venue: "arXiv",
      era: 5,
      impact: 1,
      oneLiner: "A vision-language foundation model for retinal imaging \u2014 proving that the foundation model paradigm works for specialized medical domains.",
      problem: "Medical imaging classifiers needed large labeled datasets for each specific disease. Zero-shot and few-shot classification in medical domains was unreliable with general-purpose models.",
      insight: "Apply the CLIP-style contrastive pretraining paradigm to retinal images paired with clinical text descriptions. FLAIR creates a vision-language model specialized for ophthalmology that enables zero-shot and few-shot classification of retinal diseases with minimal labeled data.",
      holds: "Medical foundation models are an active and growing field. The approach of domain-specific vision-language pretraining is being applied to radiology, pathology, and dermatology.",
      superseded: "General improvements in vision-language models continue. More diverse retinal datasets and multi-modal clinical data integration will improve future models.",
      practitioner: "This is the model I used in my Master's research \u2014 achieving 0.92 AUROC for retinal disease detection with only 5-20% labels. It demonstrates how the foundation model paradigm (papers 20, 28, 29) translates to real clinical impact. The AI Atlas comes full circle here.",
      tags: ["medical-ai", "vision-language", "foundation-model", "retinal-imaging", "my-research"],
      deps: [20, 28, 29, 43, 46, 48],
      unlocks: [],
      link: "https://arxiv.org/abs/2308.07898"
    }
  ]
};
